<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NexusUnleashed.Realm\NexusUnleashed.Realm.csproj" />
    <ProjectReference Include="..\..\src\NexusUnleashed.Network\NexusUnleashed.Network.csproj" />
    <ProjectReference Include="..\..\src\NexusUnleashed.Cryptography\NexusUnleashed.Cryptography.csproj" />
  </ItemGroup>
</Project>
