using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Gen;

public static class TableCodeGen
{
    private static string ClrType(FieldType t) => t switch
    {
        FieldType.UInt => "uint",
        FieldType.Float => "float",
        FieldType.Bool => "bool",
        FieldType.ULong => "ulong",
        FieldType.String => "string",
        _ => "uint",
    };

    private static string ReadExpr(FieldType t, int index) => t switch
    {
        FieldType.UInt => $"(uint)row[{index}]",
        FieldType.Float => $"(float)row[{index}]",
        FieldType.Bool => $"((uint)row[{index}]) != 0",
        FieldType.ULong => $"(ulong)row[{index}]",
        FieldType.String => $"(string)row[{index}]",
        _ => $"(uint)row[{index}]",
    };

    private static string Ident(string raw, HashSet<string> used)
    {
        var sb = new StringBuilder();
        foreach (char c in raw)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        string s = sb.ToString();
        if (s.Length == 0 || char.IsDigit(s[0])) s = "_" + s;
        s = char.ToUpperInvariant(s[0]) + s[1..];
        string baseName = s; int n = 2;
        while (!used.Add(s)) s = baseName + (n++);
        return s;
    }

    private static char ToUpperInvariantFirst(char c) => char.ToUpperInvariant(c);

    public static string Generate(string tblPath, string ns)
    {
        GameTable t = GameTableReader.ReadSchema(tblPath);
        string typeName = Ident(t.Name, new HashSet<string>());

        var used = new HashSet<string>(StringComparer.Ordinal);
        var props = new List<(string Prop, FieldType Type, int Index)>();
        for (int i = 0; i < t.Fields.Count; i++)
            props.Add((Ident(t.Fields[i].Name, used), t.Fields[i].Type, i));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated from the client table {t.Name}.tbl ({t.Fields.Count} fields).");
        sb.AppendLine("// The schema is a fact about Carbine's file; do not edit by hand - regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NexusUnleashed.GameData;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        sb.Append($"public sealed record {typeName}Entry(");
        sb.Append(string.Join(", ", props.Select(p => $"{ClrType(p.Type)} {p.Prop}")));
        sb.AppendLine(");");
        sb.AppendLine();

        sb.AppendLine($"public static class {typeName}Table");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IReadOnlyList<{typeName}Entry> Load(string tblPath)");
        sb.AppendLine("    {");
        sb.AppendLine("        var t = GameTableReader.Read(tblPath);");
        sb.AppendLine($"        var list = new List<{typeName}Entry>(t.Rows.Count);");
        sb.AppendLine("        foreach (var row in t.Rows)");
        sb.AppendLine($"            list.Add(new {typeName}Entry(");
        sb.AppendLine("                " + string.Join(",\n                ",
            props.Select(p => ReadExpr(p.Type, p.Index))));
        sb.AppendLine("            ));");
        sb.AppendLine("        return list;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
