// <auto-generated>
// Generated from the client table AccountItem.tbl (17 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AccountItemEntry(uint ID, uint Flags, uint Item2Id, uint EntitlementId, uint EntitlementCount, uint EntitlementScopeEnum, uint InstantEventEnum, uint AccountCurrencyEnum, ulong AccountCurrencyAmount, string ButtonIcon, uint PrerequisiteId, uint AccountItemCooldownGroupId, uint StoreDisplayInfoId, string StoreIdentifierUpsell, uint Creature2DisplayGroupIdGacha, uint EntitlementIdPurchase, uint GenericUnlockSetId);

public static class AccountItemTable
{
    public static IReadOnlyList<AccountItemEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AccountItemEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AccountItemEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (ulong)row[8],
                (string)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (string)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16]
            ));
        return list;
    }
}
