// <auto-generated>
// Generated from the client table AccountItemCooldownGroup.tbl (1 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AccountItemCooldownGroupEntry(uint ID);

public static class AccountItemCooldownGroupTable
{
    public static IReadOnlyList<AccountItemCooldownGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AccountItemCooldownGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AccountItemCooldownGroupEntry(
                (uint)row[0]
            ));
        return list;
    }
}
