// <auto-generated>
// Generated from the client table AccountCurrencyType.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AccountCurrencyTypeEntry(uint ID, uint LocalizedTextId, string IconName, uint AccountItemId);

public static class AccountCurrencyTypeTable
{
    public static IReadOnlyList<AccountCurrencyTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AccountCurrencyTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AccountCurrencyTypeEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
