// <auto-generated>
// Generated from the client table AchievementText.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementTextEntry(uint ID, uint LocalizedTextId);

public static class AchievementTextTable
{
    public static IReadOnlyList<AchievementTextEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementTextEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementTextEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
