// <auto-generated>
// Generated from the client table Achievement.tbl (23 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementEntry(uint ID, uint AchievementTypeId, uint AchievementCategoryId, uint Flags, uint WorldZoneId, uint LocalizedTextIdTitle, uint LocalizedTextIdDesc, uint LocalizedTextIdProgress, float PercCompletionToShow, uint ObjectId, uint ObjectIdAlt, uint Value, uint CharacterTitleId, uint PrerequisiteId, uint PrerequisiteIdServer, uint PrerequisiteIdObjective, uint PrerequisiteIdObjectiveAlt, uint AchievementIdParentTier, uint OrderIndex, uint AchievementGroupId, uint AchievementSubGroupId, uint AchievementPointEnum, string SteamAchievementName);

public static class AchievementTable
{
    public static IReadOnlyList<AchievementEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (float)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (string)row[22]
            ));
        return list;
    }
}
