// <auto-generated>
// Generated from the client table AchievementChecklist.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementChecklistEntry(uint ID, uint AchievementId, uint Bit, uint ObjectId, uint ObjectIdAlt, uint PrerequisiteId, uint PrerequisiteIdAlt);

public static class AchievementChecklistTable
{
    public static IReadOnlyList<AchievementChecklistEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementChecklistEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementChecklistEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
