// <auto-generated>
// Generated from the client table AchievementSubGroup.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementSubGroupEntry(uint ID, uint LocalizedTextId, uint Tier);

public static class AchievementSubGroupTable
{
    public static IReadOnlyList<AchievementSubGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementSubGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementSubGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
