// <auto-generated>
// Generated from the client table AchievementCategory.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementCategoryEntry(uint ID, uint LocalizedTextId, uint LocalizedTextIdFullName, uint AchievementCategoryIdParent);

public static class AchievementCategoryTable
{
    public static IReadOnlyList<AchievementCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementCategoryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
