// <auto-generated>
// Generated from the client table AchievementGroup.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AchievementGroupEntry(uint ID, uint LocalizedTextId, uint TradeSkillId);

public static class AchievementGroupTable
{
    public static IReadOnlyList<AchievementGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AchievementGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AchievementGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
