// <auto-generated>
// Generated from the client table ActionBarShortcutSet.tbl (25 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ActionBarShortcutSetEntry(uint ID, uint ShortcutType00, uint ShortcutType01, uint ShortcutType02, uint ShortcutType03, uint ShortcutType04, uint ShortcutType05, uint ShortcutType06, uint ShortcutType07, uint ShortcutType08, uint ShortcutType09, uint ShortcutType10, uint ShortcutType11, uint ObjectId00, uint ObjectId01, uint ObjectId02, uint ObjectId03, uint ObjectId04, uint ObjectId05, uint ObjectId06, uint ObjectId07, uint ObjectId08, uint ObjectId09, uint ObjectId10, uint ObjectId11);

public static class ActionBarShortcutSetTable
{
    public static IReadOnlyList<ActionBarShortcutSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ActionBarShortcutSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ActionBarShortcutSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24]
            ));
        return list;
    }
}
