// <auto-generated>
// Generated from the client table ActionSlotPrereq.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ActionSlotPrereqEntry(uint ID, uint SlotIndex, uint PrerequisiteIdUnlock);

public static class ActionSlotPrereqTable
{
    public static IReadOnlyList<ActionSlotPrereqEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ActionSlotPrereqEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ActionSlotPrereqEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
