// <auto-generated>
// Generated from the client table ArchiveCategory.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ArchiveCategoryEntry(uint ID, uint LocalizedTextId);

public static class ArchiveCategoryTable
{
    public static IReadOnlyList<ArchiveCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ArchiveCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ArchiveCategoryEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
