// <auto-generated>
// Generated from the client table ArchiveArticle.tbl (34 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ArchiveArticleEntry(uint ID, uint Creature2IdPortrait, string IconAssetPath, uint LocalizedTextIdTitle, uint LocalizedTextIdText00, uint LocalizedTextIdText01, uint LocalizedTextIdText02, uint LocalizedTextIdText03, uint LocalizedTextIdText04, uint LocalizedTextIdText05, uint ArchiveEntryId00, uint ArchiveEntryId01, uint ArchiveEntryId02, uint ArchiveEntryId03, uint ArchiveEntryId04, uint ArchiveEntryId05, uint ArchiveEntryId06, uint ArchiveEntryId07, uint ArchiveEntryId08, uint ArchiveEntryId09, uint ArchiveEntryId10, uint ArchiveEntryId11, uint ArchiveEntryId12, uint ArchiveEntryId13, uint ArchiveEntryId14, uint ArchiveEntryId15, uint ArchiveArticleFlags, uint ArchiveCategoryId00, uint ArchiveCategoryId01, uint ArchiveCategoryId02, uint LocalizedTextIdToolTip, uint WorldZoneId, uint CharacterTitleIdReward, string LinkName);

public static class ArchiveArticleTable
{
    public static IReadOnlyList<ArchiveArticleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ArchiveArticleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ArchiveArticleEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (string)row[33]
            ));
        return list;
    }
}
