// <auto-generated>
// Generated from the client table ArchiveEntryUnlockRule.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ArchiveEntryUnlockRuleEntry(uint ID, uint ArchiveEntryId, uint ArchiveEntryUnlockRuleEnum, uint ArchiveEntryUnlockRuleFlags, uint Object00, uint Object01, uint Object02, uint Object03, uint Object04, uint Object05);

public static class ArchiveEntryUnlockRuleTable
{
    public static IReadOnlyList<ArchiveEntryUnlockRuleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ArchiveEntryUnlockRuleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ArchiveEntryUnlockRuleEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
