// <auto-generated>
// Generated from the client table ArchiveEntry.tbl (21 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ArchiveEntryEntry(uint ID, uint LocalizedTextIdHeading, uint LocalizedTextIdText00, uint LocalizedTextIdText01, uint LocalizedTextIdText02, uint LocalizedTextIdText03, uint LocalizedTextIdText04, uint LocalizedTextIdText05, uint LocalizedTextIdTextScientist00, uint LocalizedTextIdTextScientist01, uint LocalizedTextIdTextScientist02, uint LocalizedTextIdTextScientist03, uint LocalizedTextIdTextScientist04, uint LocalizedTextIdTextScientist05, uint Creature2IdPortrait, string IconAssetPath, string InlineAssetPath, uint ArchiveEntryTypeEnum, uint ArchiveEntryFlags, uint ArchiveEntryHeaderEnum, uint CharacterTitleIdReward);

public static class ArchiveEntryTable
{
    public static IReadOnlyList<ArchiveEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ArchiveEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ArchiveEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (string)row[15],
                (string)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20]
            ));
        return list;
    }
}
