// <auto-generated>
// Generated from the client table ArchiveLink.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ArchiveLinkEntry(uint ID, uint ArchiveArticleIdParent, uint ArchiveArticleIdChild, uint ArchiveLinkFlags);

public static class ArchiveLinkTable
{
    public static IReadOnlyList<ArchiveLinkEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ArchiveLinkEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ArchiveLinkEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
