// <auto-generated>
// Generated from the client table AttributeMilestoneGroup.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record AttributeMilestoneGroupEntry(uint ID, uint RequiredAttributeAmount00, uint RequiredAttributeAmount01, uint RequiredAttributeAmount02, uint RequiredAttributeAmount03, uint RequiredAttributeAmount04, uint RequiredAttributeAmount05, uint RequiredAttributeAmount06, uint RequiredAttributeAmount07, uint RequiredAttributeAmount08, uint RequiredAttributeAmount09);

public static class AttributeMilestoneGroupTable
{
    public static IReadOnlyList<AttributeMilestoneGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<AttributeMilestoneGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new AttributeMilestoneGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
