// <auto-generated>
// Generated from the client table BinkMovie.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record BinkMovieEntry(uint ID, string BinkMovieAssetPath, uint Flags);

public static class BinkMovieTable
{
    public static IReadOnlyList<BinkMovieEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<BinkMovieEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new BinkMovieEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
