// <auto-generated>
// Generated from the client table BinkMovieSubtitle.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record BinkMovieSubtitleEntry(uint ID, uint BinkMovieId, uint DelayMs, uint LocalizedTextIdDisplayText);

public static class BinkMovieSubtitleTable
{
    public static IReadOnlyList<BinkMovieSubtitleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<BinkMovieSubtitleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new BinkMovieSubtitleEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
