// <auto-generated>
// Generated from the client table BugSubcategory.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record BugSubcategoryEntry(uint ID, uint BugCategoryId, uint LocalizedTextId);

public static class BugSubcategoryTable
{
    public static IReadOnlyList<BugSubcategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<BugSubcategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new BugSubcategoryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
