// <auto-generated>
// Generated from the client table CCStates.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CCStatesEntry(uint ID, uint Flags, float DefaultBreakProbability, uint LocalizedTextIdName, string SpellIcon, uint VisualEffectId00, uint VisualEffectId01, uint VisualEffectId02, uint CcStateDiminishingReturnsId);

public static class CCStatesTable
{
    public static IReadOnlyList<CCStatesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CCStatesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CCStatesEntry(
                (uint)row[0],
                (uint)row[1],
                (float)row[2],
                (uint)row[3],
                (string)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
