// <auto-generated>
// Generated from the client table CCStateDiminishingReturns.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CCStateDiminishingReturnsEntry(uint ID, uint LocalizedTextIdName);

public static class CCStateDiminishingReturnsTable
{
    public static IReadOnlyList<CCStateDiminishingReturnsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CCStateDiminishingReturnsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CCStateDiminishingReturnsEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
