// <auto-generated>
// Generated from the client table ChallengeTier.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ChallengeTierEntry(uint ID, uint Count);

public static class ChallengeTierTable
{
    public static IReadOnlyList<ChallengeTierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ChallengeTierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ChallengeTierEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
