// <auto-generated>
// Generated from the client table Challenge.tbl (22 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ChallengeEntry(uint ID, uint ChallengeTypeEnum, uint Target, uint ChallengeFlags, uint WorldZoneIdRestriction, uint TriggerVolume2IdRestriction, uint WorldZoneId, uint WorldLocation2IdIndicator, uint WorldLocation2IdStartLocation, uint CompletionCount, uint ChallengeTierId00, uint ChallengeTierId01, uint ChallengeTierId02, uint LocalizedTextIdName, uint LocalizedTextIdProgress, uint LocalizedTextIdAreaRestriction, uint LocalizedTextIdLocation, uint VirtualItemIdDisplay, uint TargetGroupIdRewardPane, uint QuestDirectionIdActive, uint QuestDirectionIdInactive, uint RewardTrackId);

public static class ChallengeTable
{
    public static IReadOnlyList<ChallengeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ChallengeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ChallengeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21]
            ));
        return list;
    }
}
