// <auto-generated>
// Generated from the client table CharacterTitle.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterTitleEntry(uint ID, uint CharacterTitleCategoryId, uint LocalizedTextIdName, uint LocalizedTextIdTitle, uint Spell4IdActivate, uint LifeTimeSeconds, uint PlayerTitleFlagsEnum, uint ScheduleId);

public static class CharacterTitleTable
{
    public static IReadOnlyList<CharacterTitleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterTitleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterTitleEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
