// <auto-generated>
// Generated from the client table CharacterCreationPreset.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCreationPresetEntry(uint Id, uint RaceId, uint Faction2Id, uint Gender, string StringPreset);

public static class CharacterCreationPresetTable
{
    public static IReadOnlyList<CharacterCreationPresetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCreationPresetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCreationPresetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (string)row[4]
            ));
        return list;
    }
}
