// <auto-generated>
// Generated from the client table CharacterCustomizationSelection.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCustomizationSelectionEntry(uint ID, uint CharacterCustomizationLabelId, uint Value, ulong Cost);

public static class CharacterCustomizationSelectionTable
{
    public static IReadOnlyList<CharacterCustomizationSelectionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCustomizationSelectionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCustomizationSelectionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (ulong)row[3]
            ));
        return list;
    }
}
