// <auto-generated>
// Generated from the client table CharacterCustomizationLabel.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCustomizationLabelEntry(uint ID, uint LocalizedTextId, uint Faction2Id, uint DisplayIndex);

public static class CharacterCustomizationLabelTable
{
    public static IReadOnlyList<CharacterCustomizationLabelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCustomizationLabelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCustomizationLabelEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
