// <auto-generated>
// Generated from the client table CharacterCreation.tbl (28 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCreationEntry(uint ID, uint ClassId, uint RaceId, uint Sex, uint FactionId, bool CostumeOnly, uint ItemId0, uint ItemId01, uint ItemId02, uint ItemId03, uint ItemId04, uint ItemId05, uint ItemId06, uint ItemId07, uint ItemId08, uint ItemId09, uint ItemId010, uint ItemId011, uint ItemId012, uint ItemId013, uint ItemId014, uint ItemId015, bool Enabled, uint CharacterCreationStartEnum, uint Xp, uint AccountCurrencyTypeIdCost, uint AccountCurrencyAmountCost, uint EntitlementIdRequired);

public static class CharacterCreationTable
{
    public static IReadOnlyList<CharacterCreationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCreationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCreationEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                ((uint)row[5]) != 0,
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                ((uint)row[22]) != 0,
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27]
            ));
        return list;
    }
}
