// <auto-generated>
// Generated from the client table CharacterCreationArmorSet.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCreationArmorSetEntry(uint ID, uint CreationGearSetEnum, uint ClassId, uint ItemDisplayId00, uint ItemDisplayId01, uint ItemDisplayId02, uint ItemDisplayId03, uint ItemDisplayId04, uint ItemDisplayId05, uint ItemDisplayId06, uint ItemDisplayId07, uint ItemDisplayId08, uint ItemDisplayId09, uint ItemDisplayId10, uint ItemDisplayId11);

public static class CharacterCreationArmorSetTable
{
    public static IReadOnlyList<CharacterCreationArmorSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCreationArmorSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCreationArmorSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14]
            ));
        return list;
    }
}
