// <auto-generated>
// Generated from the client table CharacterCustomization.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CharacterCustomizationEntry(uint ID, uint RaceId, uint Gender, uint ItemSlotId, uint ItemDisplayId, uint Flags, uint CharacterCustomizationLabelId00, uint CharacterCustomizationLabelId01, uint Value00, uint Value01);

public static class CharacterCustomizationTable
{
    public static IReadOnlyList<CharacterCustomizationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CharacterCustomizationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CharacterCustomizationEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
