// <auto-generated>
// Generated from the client table ChatChannel.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ChatChannelEntry(uint ID, string EnumName, string UniversalCommand00, string UniversalCommand01, uint LocalizedTextIdName, uint LocalizedTextIdCommand, uint LocalizedTextIdAbbreviation, uint LocalizedTextIdAlternate00, uint LocalizedTextIdAlternate01, uint Flags);

public static class ChatChannelTable
{
    public static IReadOnlyList<ChatChannelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ChatChannelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ChatChannelEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
