// <auto-generated>
// Generated from the client table CinematicRace.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CinematicRaceEntry(uint ID, uint CinematicId, uint RaceId, string MaleAssetPath, string FemaleAssetPath);

public static class CinematicRaceTable
{
    public static IReadOnlyList<CinematicRaceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CinematicRaceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CinematicRaceEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (string)row[3],
                (string)row[4]
            ));
        return list;
    }
}
