// <auto-generated>
// Generated from the client table CityDirection.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CityDirectionEntry(uint ID, uint CityDirectionTypeEnum, uint LocalizedTextIdName, uint WorldZoneId, uint WorldLocation2Id00, uint WorldLocation2Id01, uint WorldLocation2Id02, uint WorldLocation2Id03);

public static class CityDirectionTable
{
    public static IReadOnlyList<CityDirectionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CityDirectionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CityDirectionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
