// <auto-generated>
// Generated from the client table ClassSecondaryStatBonus.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ClassSecondaryStatBonusEntry(uint ID, uint UnitProperty2IdSecondaryStat00, uint UnitProperty2IdSecondaryStat01, uint UnitProperty2IdSecondaryStat02, float Modifier00, float Modifier01, float Modifier02);

public static class ClassSecondaryStatBonusTable
{
    public static IReadOnlyList<ClassSecondaryStatBonusEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ClassSecondaryStatBonusEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ClassSecondaryStatBonusEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6]
            ));
        return list;
    }
}
