// <auto-generated>
// Generated from the client table ClientEventAction.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ClientEventActionEntry(uint ID, uint ActionTypeEnum, uint ActionData00, uint ActionData01, uint LocalizedTextIdSubZoneName);

public static class ClientEventActionTable
{
    public static IReadOnlyList<ClientEventActionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ClientEventActionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ClientEventActionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
