// <auto-generated>
// Generated from the client table ClientEvent.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ClientEventEntry(uint ID, string Description, uint WorldId, uint EventTypeEnum, uint EventData, uint PrerequisiteId, uint Priority, uint DelayMS, uint ClientEventActionId);

public static class ClientEventTable
{
    public static IReadOnlyList<ClientEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ClientEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ClientEventEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
