// <auto-generated>
// Generated from the client table ClientSideInteraction.tbl (25 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ClientSideInteractionEntry(uint ID, uint InteractionType, uint Threshold, uint Duration, uint IncrementValue, uint WindowSize, uint Decay, uint Flags, uint TapTime0, uint TapTime1, uint VisualEffectId0, uint VisualEffectId1, uint VisualEffectId2, uint VisualEffectId3, uint VisualEffectIdTarget00, uint VisualEffectIdTarget01, uint VisualEffectIdTarget02, uint VisualEffectIdTarget03, uint VisualEffectIdTarget04, uint VisualEffectIdCaster00, uint VisualEffectIdCaster01, uint VisualEffectIdCaster02, uint VisualEffectIdCaster03, uint VisualEffectIdCaster04, uint LocalizedTextIdContext);

public static class ClientSideInteractionTable
{
    public static IReadOnlyList<ClientSideInteractionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ClientSideInteractionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ClientSideInteractionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24]
            ));
        return list;
    }
}
