// <auto-generated>
// Generated from the client table ColorShift.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ColorShiftEntry(uint ID, string TexturePath, uint LocalizedTextId, string PreviewSwatchIcon);

public static class ColorShiftTable
{
    public static IReadOnlyList<ColorShiftEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ColorShiftEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ColorShiftEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (string)row[3]
            ));
        return list;
    }
}
