// <auto-generated>
// Generated from the client table CombatReward.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CombatRewardEntry(uint ID, uint CombatRewardTypeEnum, uint LocalizedTextIdCombatFloater, uint LocalizedTextIdCombatLogMessage, uint VisualEffectIdVisual00, uint VisualEffectIdVisual01);

public static class CombatRewardTable
{
    public static IReadOnlyList<CombatRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CombatRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CombatRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
