// <auto-generated>
// Generated from the client table CommunicatorMessages.tbl (28 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CommunicatorMessagesEntry(uint ID, uint LocalizedTextIdMessage, uint Delay, uint Flags, uint CreatureId, uint WorldId, uint WorldZoneId, uint MinLevel, uint MaxLevel, uint Quest00, uint Quest01, uint Quest02, uint State00, uint State01, uint State02, uint FactionId, uint ClassId, uint RaceId, uint FactionIdReputation, uint ReputationMin, uint ReputationMax, uint QuestIdDelivered, uint PrerequisiteId, uint DisplayDuration, uint CommunicatorMessagesIdNext, uint CommunicatorPortraitPlacementEnum, uint CommunicatorOverlayEnum, uint CommunicatorBackgroundEnum);

public static class CommunicatorMessagesTable
{
    public static IReadOnlyList<CommunicatorMessagesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CommunicatorMessagesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CommunicatorMessagesEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27]
            ));
        return list;
    }
}
