// <auto-generated>
// Generated from the client table ComponentRegionRect.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ComponentRegionRectEntry(uint ID, uint RegionId, uint RectMinX, uint RectMinY, uint RectLimX, uint RectLimY, uint ComponentLayoutId);

public static class ComponentRegionRectTable
{
    public static IReadOnlyList<ComponentRegionRectEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ComponentRegionRectEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ComponentRegionRectEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
