// <auto-generated>
// Generated from the client table ComponentRegion.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ComponentRegionEntry(uint ID, string EnumName, uint ComponentMap);

public static class ComponentRegionTable
{
    public static IReadOnlyList<ComponentRegionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ComponentRegionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ComponentRegionEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
