// <auto-generated>
// Generated from the client table CostumeSpecies.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CostumeSpeciesEntry(uint ID, uint ComponentLayoutId, string EnumName);

public static class CostumeSpeciesTable
{
    public static IReadOnlyList<CostumeSpeciesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CostumeSpeciesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CostumeSpeciesEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2]
            ));
        return list;
    }
}
