// <auto-generated>
// Generated from the client table Creature2ModelInfo.tbl (59 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2ModelInfoEntry(uint ID, string AssetPath, string AssetTexture0, string AssetTexture1, uint ModelTextureId0, uint ModelTextureId1, uint CreatureMaterialEnum, float Scale, float HitRadius, float WalkLand, float WalkAir, float WalkWater, float WalkHover, float RunLand, float RunAir, float RunWater, float RunHover, uint ItemVisualTypeIdFeet, float SwimWaterDepth, uint Race, uint Sex, uint ItemDisplayId00, uint ItemDisplayId01, uint ItemDisplayId02, uint ItemDisplayId03, uint ItemDisplayId04, uint ItemDisplayId05, uint ItemDisplayId06, uint ItemDisplayId07, uint ItemDisplayId08, uint ItemDisplayId09, uint ItemDisplayId10, uint ItemDisplayId11, uint ItemDisplayId12, uint ItemDisplayId13, uint ItemDisplayId14, uint ItemDisplayId15, uint ItemDisplayId16, uint ItemDisplayId17, uint ItemDisplayId18, uint ItemDisplayId19, uint ModelMeshId00, uint ModelMeshId01, uint ModelMeshId02, uint ModelMeshId03, uint ModelMeshId04, uint ModelMeshId05, uint ModelMeshId06, uint ModelMeshId07, uint ModelMeshId08, uint ModelMeshId09, uint ModelMeshId10, uint ModelMeshId11, uint ModelMeshId12, uint ModelMeshId13, uint ModelMeshId14, uint ModelMeshId15, float GroundOffsetHover, float GroundOffsetFly);

public static class Creature2ModelInfoTable
{
    public static IReadOnlyList<Creature2ModelInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2ModelInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2ModelInfoEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16],
                (uint)row[17],
                (float)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (uint)row[41],
                (uint)row[42],
                (uint)row[43],
                (uint)row[44],
                (uint)row[45],
                (uint)row[46],
                (uint)row[47],
                (uint)row[48],
                (uint)row[49],
                (uint)row[50],
                (uint)row[51],
                (uint)row[52],
                (uint)row[53],
                (uint)row[54],
                (uint)row[55],
                (uint)row[56],
                (float)row[57],
                (float)row[58]
            ));
        return list;
    }
}
