// <auto-generated>
// Generated from the client table Creature2OverrideProperties.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2OverridePropertiesEntry(uint ID, uint Creature2Id, uint UnitPropertyIndex, float UnitPropertyValue);

public static class Creature2OverridePropertiesTable
{
    public static IReadOnlyList<Creature2OverridePropertiesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2OverridePropertiesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2OverridePropertiesEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3]
            ));
        return list;
    }
}
