// <auto-generated>
// Generated from the client table Creature2Action.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2ActionEntry(uint ID, string Description, uint CreatureActionSetId, uint State, uint Event, uint OrderIndex, uint DelayMS, uint Action, uint ActionData00, uint ActionData01, uint VisualEffectId, uint PrerequisiteId);

public static class Creature2ActionTable
{
    public static IReadOnlyList<Creature2ActionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2ActionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2ActionEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
