// <auto-generated>
// Generated from the client table Creature2DisplayInfo.tbl (78 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2DisplayInfoEntry(uint ID, uint StatusFlags, string AssetPath, string AssetTexture00, string AssetTexture01, string AssetTexture02, string AssetTexture03, string AssetTexture04, string AssetTexture05, uint ModelTextureId00, uint ModelTextureId01, uint ModelTextureId02, uint ModelTextureId03, uint ModelTextureId04, uint ModelTextureId05, string ColorShiftTexturePath, uint ColorShiftTextureIdMask, uint MaterialDataIdSkinColor0, uint MaterialDataIdSkinColor1, uint MaterialDataIdWeaponColor0, uint MaterialDataIdWeaponColor1, uint MaterialDataIdArmorColor0, uint MaterialDataIdArmorColor1, uint MaterialDataIdDefault0, uint MaterialDataIdDefault1, uint CreatureMaterialEnum, float Scale, float HitRadius, float WalkLand, float WalkAir, float WalkWater, float WalkHover, float RunLand, float RunAir, float RunWater, float RunHover, uint ItemVisualTypeIdFeet, float SwimWaterDepth, uint RaceId, uint Sex, uint ItemDisplayId00, uint ItemDisplayId01, uint ItemDisplayId02, uint ItemDisplayId03, uint ItemDisplayId04, uint ItemDisplayId05, uint ItemDisplayId06, uint ItemDisplayId07, uint ItemDisplayId08, uint ItemDisplayId09, uint ItemDisplayId10, uint ItemDisplayId11, uint ItemDisplayId12, uint ItemDisplayId13, uint ItemDisplayId14, uint ItemDisplayId15, uint ItemDisplayId16, uint ItemDisplayId17, uint ItemDisplayId18, uint ItemDisplayId19, uint ModelMeshId00, uint ModelMeshId01, uint ModelMeshId02, uint ModelMeshId03, uint ModelMeshId04, uint ModelMeshId05, uint ModelMeshId06, uint ModelMeshId07, uint ModelMeshId08, uint ModelMeshId09, uint ModelMeshId10, uint ModelMeshId11, uint ModelMeshId12, uint ModelMeshId13, uint ModelMeshId14, uint ModelMeshId15, float GroundOffsetHover, float GroundOffsetFly);

public static class Creature2DisplayInfoTable
{
    public static IReadOnlyList<Creature2DisplayInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2DisplayInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2DisplayInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (string)row[3],
                (string)row[4],
                (string)row[5],
                (string)row[6],
                (string)row[7],
                (string)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (string)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (float)row[26],
                (float)row[27],
                (float)row[28],
                (float)row[29],
                (float)row[30],
                (float)row[31],
                (float)row[32],
                (float)row[33],
                (float)row[34],
                (float)row[35],
                (uint)row[36],
                (float)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (uint)row[41],
                (uint)row[42],
                (uint)row[43],
                (uint)row[44],
                (uint)row[45],
                (uint)row[46],
                (uint)row[47],
                (uint)row[48],
                (uint)row[49],
                (uint)row[50],
                (uint)row[51],
                (uint)row[52],
                (uint)row[53],
                (uint)row[54],
                (uint)row[55],
                (uint)row[56],
                (uint)row[57],
                (uint)row[58],
                (uint)row[59],
                (uint)row[60],
                (uint)row[61],
                (uint)row[62],
                (uint)row[63],
                (uint)row[64],
                (uint)row[65],
                (uint)row[66],
                (uint)row[67],
                (uint)row[68],
                (uint)row[69],
                (uint)row[70],
                (uint)row[71],
                (uint)row[72],
                (uint)row[73],
                (uint)row[74],
                (uint)row[75],
                (float)row[76],
                (float)row[77]
            ));
        return list;
    }
}
