// <auto-generated>
// Generated from the client table Creature2OutfitInfo.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2OutfitInfoEntry(uint ID, uint ItemDisplayId00, uint ItemDisplayId01, uint ItemDisplayId02, uint ItemDisplayId03, uint ItemDisplayId04, uint ItemDisplayId05, uint ItemColorSetId00, uint ItemColorSetId01, uint ItemColorSetId02, uint ItemColorSetId03, uint ItemColorSetId04, uint ItemColorSetId05);

public static class Creature2OutfitInfoTable
{
    public static IReadOnlyList<Creature2OutfitInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2OutfitInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2OutfitInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
