// <auto-generated>
// Generated from the client table Creature2Resist.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2ResistEntry(uint ID, float ResistPhysicalMultiplier, float ResistTechMultiplier, float ResistMagicMultiplier);

public static class Creature2ResistTable
{
    public static IReadOnlyList<Creature2ResistEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2ResistEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2ResistEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3]
            ));
        return list;
    }
}
