// <auto-generated>
// Generated from the client table Creature2ActionSet.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2ActionSetEntry(uint ID, string Description, uint PrerequisiteId);

public static class Creature2ActionSetTable
{
    public static IReadOnlyList<Creature2ActionSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2ActionSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2ActionSetEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
