// <auto-generated>
// Generated from the client table Creature2ActionText.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2ActionTextEntry(uint ID, uint LocalizedTextIdOnEnterCombat00, uint LocalizedTextIdOnEnterCombat01, uint LocalizedTextIdOnEnterCombat02, uint LocalizedTextIdOnEnterCombat03, float ChanceToSayOnEnterCombat, uint LocalizedTextIdOnDeath00, uint LocalizedTextIdOnDeath01, uint LocalizedTextIdOnDeath02, uint LocalizedTextIdOnDeath03, float ChanceToSayOnDeath, uint LocalizedTextIdOnKill00, uint LocalizedTextIdOnKill01, uint LocalizedTextIdOnKill02, uint LocalizedTextIdOnKill03, float ChanceToSayOnKill);

public static class Creature2ActionTextTable
{
    public static IReadOnlyList<Creature2ActionTextEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2ActionTextEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2ActionTextEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (float)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (float)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (float)row[15]
            ));
        return list;
    }
}
