// <auto-generated>
// Generated from the client table Creature2DisplayGroupEntry.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Creature2DisplayGroupEntryEntry(uint Id, uint Creature2DisplayGroupId, uint Creature2DisplayInfoId, uint Weight);

public static class Creature2DisplayGroupEntryTable
{
    public static IReadOnlyList<Creature2DisplayGroupEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Creature2DisplayGroupEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Creature2DisplayGroupEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
