// <auto-generated>
// Generated from the client table CurrencyType.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CurrencyTypeEntry(uint ID, string Description, uint LocalizedTextId, string IconName, ulong CapAmount);

public static class CurrencyTypeTable
{
    public static IReadOnlyList<CurrencyTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CurrencyTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CurrencyTypeEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (string)row[3],
                (ulong)row[4]
            ));
        return list;
    }
}
