// <auto-generated>
// Generated from the client table CustomizationParameter.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CustomizationParameterEntry(uint ID, uint LocalizedTextId, uint SclX, uint SclY, uint SclZ, uint RotX, uint RotY, uint RotZ, uint PosX, uint PosY, uint PosZ);

public static class CustomizationParameterTable
{
    public static IReadOnlyList<CustomizationParameterEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CustomizationParameterEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CustomizationParameterEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
