// <auto-generated>
// Generated from the client table CustomerSurvey.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record CustomerSurveyEntry(uint ID, uint CustomerSurveyTypeEnum, uint LocalizedTextIdOverrideTitle, uint LocalizedTextIdQuestion00, uint LocalizedTextIdQuestion01, uint LocalizedTextIdQuestion02);

public static class CustomerSurveyTable
{
    public static IReadOnlyList<CustomerSurveyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<CustomerSurveyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new CustomerSurveyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
