// <auto-generated>
// Generated from the client table DailyLoginReward.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record DailyLoginRewardEntry(uint Id, uint LoginDay, uint DailyLoginRewardTypeEnum, uint RewardObjectValue, uint DailyLoginRewardTierEnum);

public static class DailyLoginRewardTable
{
    public static IReadOnlyList<DailyLoginRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<DailyLoginRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new DailyLoginRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
