// <auto-generated>
// Generated from the client table DatacubeVolume.tbl (19 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record DatacubeVolumeEntry(uint ID, uint LocalizedTextIdName, string AssetPath, uint DatacubeId00, uint DatacubeId01, uint DatacubeId02, uint DatacubeId03, uint DatacubeId04, uint DatacubeId05, uint DatacubeId06, uint DatacubeId07, uint DatacubeId08, uint DatacubeId09, uint DatacubeId10, uint DatacubeId11, uint DatacubeId12, uint DatacubeId13, uint DatacubeId14, uint DatacubeId15);

public static class DatacubeVolumeTable
{
    public static IReadOnlyList<DatacubeVolumeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<DatacubeVolumeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new DatacubeVolumeEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18]
            ));
        return list;
    }
}
