// <auto-generated>
// Generated from the client table Datacube.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record DatacubeEntry(uint ID, uint DatacubeTypeEnum, uint LocalizedTextIdTitle, uint LocalizedTextIdText00, uint LocalizedTextIdText01, uint LocalizedTextIdText02, uint LocalizedTextIdText03, uint LocalizedTextIdText04, uint LocalizedTextIdText05, uint SoundEventId, uint WorldZoneId, uint UnlockCount, string AssetPathImage, uint DatacubeFactionEnum, uint WorldLocation2Id, uint QuestDirectionId);

public static class DatacubeTable
{
    public static IReadOnlyList<DatacubeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<DatacubeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new DatacubeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (string)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15]
            ));
        return list;
    }
}
