// <auto-generated>
// Generated from the client table DistanceDamageModifier.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record DistanceDamageModifierEntry(uint ID, float DistancePercent00, float DistancePercent01, float DistancePercent02, float DistancePercent03, float DistancePercent04, float DamageModifier00, float DamageModifier01, float DamageModifier02, float DamageModifier03, float DamageModifier04);

public static class DistanceDamageModifierTable
{
    public static IReadOnlyList<DistanceDamageModifierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<DistanceDamageModifierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new DistanceDamageModifierEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10]
            ));
        return list;
    }
}
