// <auto-generated>
// Generated from the client table DyeColorRamp.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record DyeColorRampEntry(uint ID, uint Flags, uint LocalizedTextIdName, uint RampIndex, float CostMultiplier, uint ComponentMapEnum, uint PrerequisiteId);

public static class DyeColorRampTable
{
    public static IReadOnlyList<DyeColorRampEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<DyeColorRampEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new DyeColorRampEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (float)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
