// <auto-generated>
// Generated from the client table EldanAugmentationCategory.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record EldanAugmentationCategoryEntry(uint ID, uint EldanAugmentationCategoryIdTier2Category00, uint EldanAugmentationCategoryIdTier2Category01, uint Tier2CostAmount00, uint Tier2CostAmount01, uint Tier3CostAmount00, uint Tier3CostAmount01, uint LocalizedTextIdName);

public static class EldanAugmentationCategoryTable
{
    public static IReadOnlyList<EldanAugmentationCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<EldanAugmentationCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new EldanAugmentationCategoryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
