// <auto-generated>
// Generated from the client table Emotes.tbl (26 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record EmotesEntry(uint ID, uint LocalizedTextIdNoArgToAll, uint LocalizedTextIdNoArgToSelf, uint NoArgAnim, uint LocalizedTextIdArgToAll, uint LocalizedTextIdArgToArg, uint LocalizedTextIdArgToSelf, uint ArgAnim, uint LocalizedTextIdSelfToAll, uint LocalizedTextIdSelfToSelf, uint SelfAnim, bool SheathWeapons, bool TurnToFace, bool TextReplaceable, bool ChangesStandState, uint StandState, uint LocalizedTextIdCommand, uint LocalizedTextIdNotFoundToAll, uint LocalizedTextIdNotFoundToSelf, uint NotFoundAnim, uint TextReplaceAnim, uint ModelSequenceIdStandState, uint VisualEffectId, uint Flags, string UniversalCommand00, string UniversalCommand01);

public static class EmotesTable
{
    public static IReadOnlyList<EmotesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<EmotesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new EmotesEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                ((uint)row[11]) != 0,
                ((uint)row[12]) != 0,
                ((uint)row[13]) != 0,
                ((uint)row[14]) != 0,
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (string)row[24],
                (string)row[25]
            ));
        return list;
    }
}
