// <auto-generated>
// Generated from the client table EmoteSequenceTransition.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record EmoteSequenceTransitionEntry(uint ID, uint EmotesIdTo, uint StandStateFrom, uint EmotesIdFrom, uint ModelSequenceId);

public static class EmoteSequenceTransitionTable
{
    public static IReadOnlyList<EmoteSequenceTransitionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<EmoteSequenceTransitionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new EmoteSequenceTransitionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
