// <auto-generated>
// Generated from the client table Entitlement.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record EntitlementEntry(uint ID, uint MaxCount, uint Flags, uint Spell4IdPersistentBuff, uint CharacterTitleId, uint LocalizedTextIdName, uint LocalizedTextIdDescription, string ButtonIcon);

public static class EntitlementTable
{
    public static IReadOnlyList<EntitlementEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<EntitlementEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new EntitlementEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (string)row[7]
            ));
        return list;
    }
}
