// <auto-generated>
// Generated from the client table Episode.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record EpisodeEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdBriefing, uint LocalizedTextIdEndSummary, uint Flags, uint WorldZoneId, uint PercentToDisplay, uint QuestHubIdExile, uint QuestHubIdDominion);

public static class EpisodeTable
{
    public static IReadOnlyList<EpisodeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<EpisodeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new EpisodeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
