// <auto-generated>
// Generated from the client table Faction2Relationship.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Faction2RelationshipEntry(uint ID, uint FactionId0, uint FactionId1, uint FactionLevel);

public static class Faction2RelationshipTable
{
    public static IReadOnlyList<Faction2RelationshipEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Faction2RelationshipEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Faction2RelationshipEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
