// <auto-generated>
// Generated from the client table Faction2.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Faction2Entry(uint ID, uint Faction2IdParent, uint Flags, uint LocalizedTextIdName, uint LocalizedTextIdToolTip, uint OrderIndex, uint ArchiveArticleId);

public static class Faction2Table
{
    public static IReadOnlyList<Faction2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Faction2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Faction2Entry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
