// <auto-generated>
// Generated from the client table FinishingMoveDeathVisual.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record FinishingMoveDeathVisualEntry(uint ID, uint Priority, uint DamageTypeFlags, uint Creature2MinSize, uint Creature2MaxSize, uint CreatureMaterialEnum, uint MovementStateFlags, string DeathModelAsset, uint ModelSequenceIdDeath, uint VisualEffectIdDeath00, uint VisualEffectIdDeath01, uint VisualEffectIdDeath02);

public static class FinishingMoveDeathVisualTable
{
    public static IReadOnlyList<FinishingMoveDeathVisualEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<FinishingMoveDeathVisualEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new FinishingMoveDeathVisualEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (string)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
