// <auto-generated>
// Generated from the client table FullScreenEffect.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record FullScreenEffectEntry(uint ID, string Description, string TexturePath, string ModelPath, uint Priority, uint FullScreenEffectTypeEnum, float AlphaMinStart, float AlphaMinEnd, float AlphaStart, float AlphaEnd, float HzStart, float HzEnd, float SaturationStart, float SaturationEnd);

public static class FullScreenEffectTable
{
    public static IReadOnlyList<FullScreenEffectEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<FullScreenEffectEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new FullScreenEffectEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13]
            ));
        return list;
    }
}
