// <auto-generated>
// Generated from the client table GameFormula.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GameFormulaEntry(uint ID, uint Dataint0, uint Dataint01, uint Dataint02, uint Dataint03, uint Dataint04, float Datafloat0, float Datafloat01, float Datafloat02, float Datafloat03, float Datafloat04);

public static class GameFormulaTable
{
    public static IReadOnlyList<GameFormulaEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GameFormulaEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GameFormulaEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10]
            ));
        return list;
    }
}
