// <auto-generated>
// Generated from the client table GenericUnlockEntry.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GenericUnlockEntryEntry(uint ID, uint LocalizedTextIdDescription, string SpriteIcon, string SpritePreview, uint GenericUnlockTypeEnum, uint UnlockObject);

public static class GenericUnlockEntryTable
{
    public static IReadOnlyList<GenericUnlockEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GenericUnlockEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GenericUnlockEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
