// <auto-generated>
// Generated from the client table GenericMapNode.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GenericMapNodeEntry(uint ID, uint GenericMapId, uint WorldLocation2Id, uint LocalizedTextIdName, uint LocalizedTextIdDescription, string SpritePath, uint GenericMapNodeTypeEnum, uint Flags);

public static class GenericMapNodeTable
{
    public static IReadOnlyList<GenericMapNodeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GenericMapNodeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GenericMapNodeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
