// <auto-generated>
// Generated from the client table GenericUnlockSet.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GenericUnlockSetEntry(uint ID, uint GenericUnlockScopeEnum, uint GenericUnlockEntryId00, uint GenericUnlockEntryId01, uint GenericUnlockEntryId02, uint GenericUnlockEntryId03, uint GenericUnlockEntryId04, uint GenericUnlockEntryId05);

public static class GenericUnlockSetTable
{
    public static IReadOnlyList<GenericUnlockSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GenericUnlockSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GenericUnlockSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
