// <auto-generated>
// Generated from the client table GossipEntry.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GossipEntryEntry(uint ID, uint GossipSetId, uint IndexOrder, uint LocalizedTextId, uint PrerequisiteId);

public static class GossipEntryTable
{
    public static IReadOnlyList<GossipEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GossipEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GossipEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
