// <auto-generated>
// Generated from the client table GuildPermission.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GuildPermissionEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdDescription, string LuaVariable, uint LocalizedTextIdCommand, uint GuildTypeEnumFlags, uint DisplayIndex);

public static class GuildPermissionTable
{
    public static IReadOnlyList<GuildPermissionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GuildPermissionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GuildPermissionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
