// <auto-generated>
// Generated from the client table GuildStandardPart.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record GuildStandardPartEntry(uint ID, uint GuildStandardPartTypeEnum, uint LocalizedTextIdName, uint ItemDisplayIdStandard);

public static class GuildStandardPartTable
{
    public static IReadOnlyList<GuildStandardPartEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<GuildStandardPartEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new GuildStandardPartEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
