// <auto-generated>
// Generated from the client table Hazard.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HazardEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdTooltip, float MeterChangeRate, uint MeterMaxValue, uint Flags, uint HazardTypeEnum, uint Spell4IdDamage, float MinDistanceToUnit, float MeterThreshold00, float MeterThreshold01, float MeterThreshold02, uint Spell4IdThresholdProc00, uint Spell4IdThresholdProc01, uint Spell4IdThresholdProc02);

public static class HazardTable
{
    public static IReadOnlyList<HazardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HazardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HazardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14]
            ));
        return list;
    }
}
