// <auto-generated>
// Generated from the client table HookAsset.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HookAssetEntry(uint ID, string Asset, float Scale, float OffsetX, float OffsetY, float OffsetZ, float RotationX, float RotationY, float RotationZ);

public static class HookAssetTable
{
    public static IReadOnlyList<HookAssetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HookAssetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HookAssetEntry(
                (uint)row[0],
                (string)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8]
            ));
        return list;
    }
}
