// <auto-generated>
// Generated from the client table HookType.tbl (1 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HookTypeEntry(uint ID);

public static class HookTypeTable
{
    public static IReadOnlyList<HookTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HookTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HookTypeEntry(
                (uint)row[0]
            ));
        return list;
    }
}
