// <auto-generated>
// Generated from the client table HousingWarplotPlugInfo.tbl (18 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingWarplotPlugInfoEntry(uint ID, uint HousingPlugItemId, uint MaintenanceCost, uint UpgradeCost00, uint UpgradeCost01, uint UpgradeCost02, uint Spell4IdAbility00, uint Spell4IdAbility01, uint Spell4IdAbility02, uint Spell4IdAbility03, uint Spell4IdAbility04, uint Spell4IdAbility05, uint Spell4IdAbility06, uint Spell4IdAbility07, uint Spell4IdAbility08, uint Spell4IdAbility09, uint Spell4IdAbility10, uint Spell4IdAbility11);

public static class HousingWarplotPlugInfoTable
{
    public static IReadOnlyList<HousingWarplotPlugInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingWarplotPlugInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingWarplotPlugInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17]
            ));
        return list;
    }
}
