// <auto-generated>
// Generated from the client table HousingMannequinPose.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingMannequinPoseEntry(uint ID, string EnumName, uint LocalizedTextId, uint ModelSequenceId);

public static class HousingMannequinPoseTable
{
    public static IReadOnlyList<HousingMannequinPoseEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingMannequinPoseEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingMannequinPoseEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
