// <auto-generated>
// Generated from the client table HousingContributionType.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingContributionTypeEntry(uint ID, string Description, string EnumName);

public static class HousingContributionTypeTable
{
    public static IReadOnlyList<HousingContributionTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingContributionTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingContributionTypeEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2]
            ));
        return list;
    }
}
