// <auto-generated>
// Generated from the client table HousingContributionInfo.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingContributionInfoEntry(uint ID, uint HousingContributionTypeId, uint ContributionPointRequirement, uint Item2IdTier00, uint Item2IdTier01, uint Item2IdTier02, uint Item2IdTier03, uint Item2IdTier04, uint ContributionPointValueTier00, uint ContributionPointValueTier01, uint ContributionPointValueTier02, uint ContributionPointValueTier03, uint ContributionPointValueTier04);

public static class HousingContributionInfoTable
{
    public static IReadOnlyList<HousingContributionInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingContributionInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingContributionInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
