// <auto-generated>
// Generated from the client table HousingMapInfo.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingMapInfoEntry(uint ID, uint WorldId, uint PrivatePropertyCount, uint PublicPropertyCount);

public static class HousingMapInfoTable
{
    public static IReadOnlyList<HousingMapInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingMapInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingMapInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
