// <auto-generated>
// Generated from the client table HousingPlugItem.tbl (48 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingPlugItemEntry(uint ID, uint LocalizedTextIdName, uint HousingPlotTypeId, uint LocalizedTextIdTooltip, uint WorldIdPlug00, uint WorldIdPlug01, uint WorldIdPlug02, uint WorldIdPlug03, uint Flags, uint HousingResourceIdProvided00, uint HousingResourceIdProvided01, uint HousingResourceIdProvided02, uint HousingResourceIdProvided03, uint HousingResourceIdProvided04, uint HousingResourceIdPrerequisite00, uint HousingResourceIdPrerequisite01, uint HousingResourceIdPrerequisite02, uint HousingFeatureTypeFlags, uint HousingContributionInfoId00, uint HousingContributionInfoId01, uint HousingContributionInfoId02, uint HousingContributionInfoId03, uint HousingContributionInfoId04, uint HousingPlugItemIdNextUpgrade, uint LocalizedTextIdPrereqTooltip00, uint LocalizedTextIdPrereqTooltip01, uint LocalizedTextIdPrereqTooltip02, uint PrerequisiteId00, uint PrerequisiteId01, uint PrerequisiteId02, uint PrerequisiteIdUnlock, uint HousingBuildId, uint HousingUpkeepTypeEnum, uint UpkeepCharges, float UpkeepTime, uint HousingContributionInfoIdUpkeepCost00, uint HousingContributionInfoIdUpkeepCost01, uint HousingContributionInfoIdUpkeepCost02, uint HousingContributionInfoIdUpkeepCost03, uint HousingContributionInfoIdUpkeepCost04, uint GameFormulaIdHousingBuildBonus, string ScreenshotSprite00, string ScreenshotSprite01, string ScreenshotSprite02, string ScreenshotSprite03, string ScreenshotSprite04, uint HousingPlugTypeEnum, uint AccountItemIdUpsell);

public static class HousingPlugItemTable
{
    public static IReadOnlyList<HousingPlugItemEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingPlugItemEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingPlugItemEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (float)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (string)row[41],
                (string)row[42],
                (string)row[43],
                (string)row[44],
                (string)row[45],
                (uint)row[46],
                (uint)row[47]
            ));
        return list;
    }
}
