// <auto-generated>
// Generated from the client table HousingResidenceInfo.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingResidenceInfoEntry(uint ID, uint HousingDecorInfoIdDefaultRoof, uint HousingDecorInfoIdDefaultEntryway, uint HousingDecorInfoIdDefaultDoor, uint HousingWallpaperInfoIdDefault, uint WorldLocation2IdInside00, uint WorldLocation2IdInside01, uint WorldLocation2IdInside02, uint WorldLocation2IdInside03, uint WorldLocation2IdOutside00, uint WorldLocation2IdOutside01, uint WorldLocation2IdOutside02, uint WorldLocation2IdOutside03);

public static class HousingResidenceInfoTable
{
    public static IReadOnlyList<HousingResidenceInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingResidenceInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingResidenceInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
