// <auto-generated>
// Generated from the client table HousingDecorType.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingDecorTypeEntry(uint ID, uint LocalizedTextId, string LuaString);

public static class HousingDecorTypeTable
{
    public static IReadOnlyList<HousingDecorTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingDecorTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingDecorTypeEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2]
            ));
        return list;
    }
}
