// <auto-generated>
// Generated from the client table HousingPlotInfo.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingPlotInfoEntry(uint ID, uint WorldSocketId, uint PlotType, uint HousingPropertyInfoId, uint HousingPropertyPlotIndex, uint HousingPlugItemIdDefault);

public static class HousingPlotInfoTable
{
    public static IReadOnlyList<HousingPlotInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingPlotInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingPlotInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
