// <auto-generated>
// Generated from the client table HousingWarplotBossToken.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingWarplotBossTokenEntry(uint ID, uint Spell4IdSummon, uint MinimumUpgradeTierEnum, uint HousingPlugItemIdLinked);

public static class HousingWarplotBossTokenTable
{
    public static IReadOnlyList<HousingWarplotBossTokenEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingWarplotBossTokenEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingWarplotBossTokenEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
