// <auto-generated>
// Generated from the client table HousingDecorInfo.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingDecorInfoEntry(uint ID, uint HousingDecorTypeId, uint HookTypeId, uint LocalizedTextIdName, uint Flags, uint HookAssetId, uint Cost, uint CostCurrencyTypeId, uint Creature2IdActiveProp, uint PrerequisiteIdUnlock, uint Spell4IdInteriorBuff, uint HousingDecorLimitCategoryId, string AltPreviewAsset, string AltEditAsset, float MinScale, float MaxScale);

public static class HousingDecorInfoTable
{
    public static IReadOnlyList<HousingDecorInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingDecorInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingDecorInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (string)row[12],
                (string)row[13],
                (float)row[14],
                (float)row[15]
            ));
        return list;
    }
}
