// <auto-generated>
// Generated from the client table HousingDecorLimitCategory.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingDecorLimitCategoryEntry(uint ID, uint DecorLimit);

public static class HousingDecorLimitCategoryTable
{
    public static IReadOnlyList<HousingDecorLimitCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingDecorLimitCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingDecorLimitCategoryEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
