// <auto-generated>
// Generated from the client table HousingPropertyInfo.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingPropertyInfoEntry(uint ID, uint LocalizedTextIdName, uint WorldId, uint HousingMapInfoId, uint Cost, uint HousingFacingEnum, uint WorldLocation2Id, uint WorldZoneId, uint HousingPropertyTypeId, uint WorldLayerIdDefault00, uint WorldLayerIdDefault01, uint WorldLayerIdDefault02, uint WorldLayerIdDefault03);

public static class HousingPropertyInfoTable
{
    public static IReadOnlyList<HousingPropertyInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingPropertyInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingPropertyInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
