// <auto-generated>
// Generated from the client table HousingBuild.tbl (22 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingBuildEntry(uint ID, string Description, string AssetPath, uint ConstructionEffectsId, float BuildPreDelayTimeMS, float BuildPostDelayTimeMS, float BuildTime00, float BuildTime01, float BuildTime02, float BuildTime03, float BuildTime04, float BuildTime05, float BuildTime06, float BuildTime07, uint ModelSequenceId00, uint ModelSequenceId01, uint ModelSequenceId02, uint ModelSequenceId03, uint ModelSequenceId04, uint ModelSequenceId05, uint ModelSequenceId06, uint ModelSequenceId07);

public static class HousingBuildTable
{
    public static IReadOnlyList<HousingBuildEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingBuildEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingBuildEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (uint)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21]
            ));
        return list;
    }
}
