// <auto-generated>
// Generated from the client table HousingResource.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record HousingResourceEntry(uint ID, uint LocalizedTextIdName);

public static class HousingResourceTable
{
    public static IReadOnlyList<HousingResourceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<HousingResourceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new HousingResourceEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
