// <auto-generated>
// Generated from the client table InputAction.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record InputActionEntry(uint ID, string EnumName, uint LocalizedTextId, uint InputActionCategoryId, bool CanHaveUpDownState, uint DisplayIndex);

public static class InputActionTable
{
    public static IReadOnlyList<InputActionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<InputActionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new InputActionEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                ((uint)row[4]) != 0,
                (uint)row[5]
            ));
        return list;
    }
}
