// <auto-generated>
// Generated from the client table InstancePortal.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record InstancePortalEntry(uint ID, uint LocalizedTextIdName, uint MinLevel, uint MaxLevel, uint ExpectedCompletionTime, uint InstancePortalTypeEnum);

public static class InstancePortalTable
{
    public static IReadOnlyList<InstancePortalEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<InstancePortalEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new InstancePortalEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
