// <auto-generated>
// Generated from the client table ItemSlot.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemSlotEntry(uint ID, string EnumName, uint EquippedSlotFlags, float ArmorModifier, float ItemLevelModifier, uint SlotBonus, uint GlyphSlotBonus, uint MinLevel);

public static class ItemSlotTable
{
    public static IReadOnlyList<ItemSlotEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemSlotEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemSlotEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
