// <auto-generated>
// Generated from the client table ItemRandomStat.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemRandomStatEntry(uint ID, uint ItemRandomStatGroupId, float Weight, uint ItemStatTypeEnum, uint ItemStatData);

public static class ItemRandomStatTable
{
    public static IReadOnlyList<ItemRandomStatEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemRandomStatEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemRandomStatEntry(
                (uint)row[0],
                (uint)row[1],
                (float)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
