// <auto-generated>
// Generated from the client table ItemStat.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemStatEntry(uint ID, uint ItemStatTypeEnum00, uint ItemStatTypeEnum01, uint ItemStatTypeEnum02, uint ItemStatTypeEnum03, uint ItemStatTypeEnum04, uint ItemStatData00, uint ItemStatData01, uint ItemStatData02, uint ItemStatData03, uint ItemStatData04);

public static class ItemStatTable
{
    public static IReadOnlyList<ItemStatEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemStatEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemStatEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
