// <auto-generated>
// Generated from the client table ItemSetBonus.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemSetBonusEntry(uint ID, uint RequiredPower, uint UnitProperty2Id, float Scalar, float Offset, uint Spell4Id);

public static class ItemSetBonusTable
{
    public static IReadOnlyList<ItemSetBonusEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemSetBonusEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemSetBonusEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
