// <auto-generated>
// Generated from the client table ItemSpecial.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemSpecialEntry(uint ID, uint PrerequisiteIdGeneric00, uint LocalizedTextIdName, uint Spell4IdOnEquip, uint Spell4IdOnActivate);

public static class ItemSpecialTable
{
    public static IReadOnlyList<ItemSpecialEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemSpecialEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemSpecialEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
