// <auto-generated>
// Generated from the client table ItemQuality.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemQualityEntry(uint ID, float SalvageCritChance, float TurninMultiplier, float RuneCostMultiplier, float DyeCostMultiplier, uint VisualEffectIdLoot, float IconColorR, float IconColorG, float IconColorB, uint DefaultRunes, uint MaxRunes, string AssetPathDieModel, uint SoundEventIdFortuneCardFanfare);

public static class ItemQualityTable
{
    public static IReadOnlyList<ItemQualityEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemQualityEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemQualityEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (uint)row[9],
                (uint)row[10],
                (string)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
