// <auto-generated>
// Generated from the client table Item2Family.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Item2FamilyEntry(uint ID, uint LocalizedTextId, uint Flags, uint SoundEventIdEquip, float VendorMultiplier, float TurninMultiplier);

public static class Item2FamilyTable
{
    public static IReadOnlyList<Item2FamilyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Item2FamilyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Item2FamilyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (float)row[4],
                (float)row[5]
            ));
        return list;
    }
}
