// <auto-generated>
// Generated from the client table ItemBudget.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemBudgetEntry(uint ID, float Budget00, float Budget01, float Budget02, float Budget03, float Budget04);

public static class ItemBudgetTable
{
    public static IReadOnlyList<ItemBudgetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemBudgetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemBudgetEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5]
            ));
        return list;
    }
}
