// <auto-generated>
// Generated from the client table ItemImbuement.tbl (31 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemImbuementEntry(uint ID, uint Quest2Id00, uint Quest2Id01, uint Quest2Id02, uint Quest2Id03, uint Quest2Id04, uint Quest2Id05, uint Quest2Id06, uint Quest2Id07, uint Quest2Id08, uint Quest2Id09, uint Quest2Id10, uint Quest2Id11, uint Quest2Id12, uint Quest2Id13, uint Quest2Id14, uint ItemImbuementRewardId00, uint ItemImbuementRewardId01, uint ItemImbuementRewardId02, uint ItemImbuementRewardId03, uint ItemImbuementRewardId04, uint ItemImbuementRewardId05, uint ItemImbuementRewardId06, uint ItemImbuementRewardId07, uint ItemImbuementRewardId08, uint ItemImbuementRewardId09, uint ItemImbuementRewardId10, uint ItemImbuementRewardId11, uint ItemImbuementRewardId12, uint ItemImbuementRewardId13, uint ItemImbuementRewardId14);

public static class ItemImbuementTable
{
    public static IReadOnlyList<ItemImbuementEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemImbuementEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemImbuementEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30]
            ));
        return list;
    }
}
