// <auto-generated>
// Generated from the client table ItemColorSet.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemColorSetEntry(uint ID, uint DyeColorRampId00, uint DyeColorRampId01, uint DyeColorRampId02);

public static class ItemColorSetTable
{
    public static IReadOnlyList<ItemColorSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemColorSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemColorSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
