// <auto-generated>
// Generated from the client table Item2.tbl (49 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Item2Entry(uint ID, uint ItemBudgetId, uint ItemStatId, uint ItemRuneInstanceId, uint ItemQualityId, uint ItemSpecialId00, uint ItemImbuementId, uint Item2FamilyId, uint Item2CategoryId, uint Item2TypeId, uint ItemDisplayId, uint ItemSourceId, uint ClassRequired, uint RaceRequired, uint Faction2IdRequired, uint PowerLevel, uint RequiredLevel, uint RequiredItemLevel, uint PrerequisiteId, uint EquippedSlotFlags, uint MaxStackCount, uint MaxCharges, uint ExpirationTimeMinutes, uint Quest2IdActivation, uint Quest2IdActivationRequired, uint QuestObjectiveActivationRequired, uint TradeskillAdditiveId, uint TradeskillCatalystId, uint HousingDecorInfoId, uint HousingWarplotBossTokenId, uint GenericUnlockSetId, uint Flags, uint BindFlags, uint BuyFromVendorStackCount, uint CurrencyTypeId0, uint CurrencyTypeId1, uint CurrencyAmount0, uint CurrencyAmount1, uint CurrencyTypeId0SellToVendor, uint CurrencyTypeId1SellToVendor, uint CurrencyAmount0SellToVendor, uint CurrencyAmount1SellToVendor, uint ItemColorSetId, float SupportPowerPercentage, uint LocalizedTextIdName, uint LocalizedTextIdTooltip, string ButtonTemplate, string ButtonIcon, uint SoundEventIdEquip);

public static class Item2Table
{
    public static IReadOnlyList<Item2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Item2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Item2Entry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (uint)row[41],
                (uint)row[42],
                (float)row[43],
                (uint)row[44],
                (uint)row[45],
                (string)row[46],
                (string)row[47],
                (uint)row[48]
            ));
        return list;
    }
}
