// <auto-generated>
// Generated from the client table ItemDisplaySourceEntry.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemDisplaySourceEntryEntry(uint ID, uint ItemSourceId, uint Item2TypeId, uint ItemMinLevel, uint ItemMaxLevel, uint ItemDisplayId, string Icon);

public static class ItemDisplaySourceEntryTable
{
    public static IReadOnlyList<ItemDisplaySourceEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemDisplaySourceEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemDisplaySourceEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (string)row[6]
            ));
        return list;
    }
}
