// <auto-generated>
// Generated from the client table ItemDisplay.tbl (44 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemDisplayEntry(uint ID, string Description, uint Item2TypeId, string ObjectModel, string ObjectModelL, string ObjectTexture0, string ObjectTexture1, uint ModelTextureIdObject00, uint ModelTextureIdObject01, string SkinnedModel, string SkinnedModelL, string SkinnedTexture0, string SkinnedTexture1, uint ModelTextureIdSkinned00, uint ModelTextureIdSkinned01, string AttachedModel, uint ModelAttachmentIdAttached, string AttachedTexture0, string AttachedTexture1, uint ModelTextureIdAttached00, uint ModelTextureIdAttached01, uint ComponentRegionFlags, uint ComponentPriority, string SkinMaskMap, string SkinColorMap, string SkinNormalMap, string SkinDyeMap, string ArmorMaskMap, string ArmorColorMap, string ArmorNormalMap, string ArmorDyeMap, uint ModelMeshId00, uint ModelMeshId01, uint ModelMeshId02, uint ModelMeshId03, uint SoundImpactDescriptionId, uint ItemVisualTypeId, uint SoundReplaceDescriptionId, uint ItemColorSetId, uint DyeChannelFlags, uint ModelPoseId, float ModelPoseBlend, uint ShaderPreset00, uint ShaderPreset01);

public static class ItemDisplayTable
{
    public static IReadOnlyList<ItemDisplayEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemDisplayEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemDisplayEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (string)row[3],
                (string)row[4],
                (string)row[5],
                (string)row[6],
                (uint)row[7],
                (uint)row[8],
                (string)row[9],
                (string)row[10],
                (string)row[11],
                (string)row[12],
                (uint)row[13],
                (uint)row[14],
                (string)row[15],
                (uint)row[16],
                (string)row[17],
                (string)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (string)row[23],
                (string)row[24],
                (string)row[25],
                (string)row[26],
                (string)row[27],
                (string)row[28],
                (string)row[29],
                (string)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (float)row[41],
                (uint)row[42],
                (uint)row[43]
            ));
        return list;
    }
}
