// <auto-generated>
// Generated from the client table ItemProficiency.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemProficiencyEntry(uint ID, uint BitMask, uint LocalizedTextIdString);

public static class ItemProficiencyTable
{
    public static IReadOnlyList<ItemProficiencyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemProficiencyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemProficiencyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
