// <auto-generated>
// Generated from the client table ItemRuneSlotRandomization.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemRuneSlotRandomizationEntry(uint ID, uint MicrochipTypeEnum, uint ItemRoleFlagBitMask, float RandomWeight);

public static class ItemRuneSlotRandomizationTable
{
    public static IReadOnlyList<ItemRuneSlotRandomizationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemRuneSlotRandomizationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemRuneSlotRandomizationEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3]
            ));
        return list;
    }
}
