// <auto-generated>
// Generated from the client table Item2Type.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Item2TypeEntry(uint ID, uint LocalizedTextId, uint ItemSlotId, uint SoundEventIdLoot, uint SoundEventIdEquip, uint Flags, float VendorMultiplier, float TurninMultiplier, uint Item2CategoryId, float ReferenceMuzzleX, float ReferenceMuzzleY, float ReferenceMuzzleZ);

public static class Item2TypeTable
{
    public static IReadOnlyList<Item2TypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Item2TypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Item2TypeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (float)row[6],
                (float)row[7],
                (uint)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11]
            ));
        return list;
    }
}
