// <auto-generated>
// Generated from the client table ItemRuneInstance.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemRuneInstanceEntry(uint ID, uint DefinedSocketCount, uint DefinedSocketType00, uint DefinedSocketType01, uint DefinedSocketType02, uint DefinedSocketType03, uint DefinedSocketType04, uint DefinedSocketType05, uint DefinedSocketType06, uint DefinedSocketType07, uint ItemSetId, uint ItemSetPower, uint SocketCountMax);

public static class ItemRuneInstanceTable
{
    public static IReadOnlyList<ItemRuneInstanceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemRuneInstanceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemRuneInstanceEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
