// <auto-generated>
// Generated from the client table ItemSet.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ItemSetEntry(uint ID, uint LocalizedTextId, uint ItemSetBonusId00, uint ItemSetBonusId01, uint ItemSetBonusId02, uint ItemSetBonusId03, uint ItemSetBonusId04, uint ItemSetBonusId05, uint ItemSetBonusId06, uint ItemSetBonusId07, uint ItemSetBonusId08, uint ItemSetBonusId09, uint ItemSetBonusId10, uint ItemSetBonusId11);

public static class ItemSetTable
{
    public static IReadOnlyList<ItemSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ItemSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ItemSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
