// <auto-generated>
// Generated from the client table Language.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LanguageEntry(uint ID, string LanguageTag, string ClientLanguageTag, uint SoundAvailabilityIndexFemale);

public static class LanguageTable
{
    public static IReadOnlyList<LanguageEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LanguageEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LanguageEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
