// <auto-generated>
// Generated from the client table LevelUpUnlockType.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LevelUpUnlockTypeEntry(uint ID, uint LocalizedTextId);

public static class LevelUpUnlockTypeTable
{
    public static IReadOnlyList<LevelUpUnlockTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LevelUpUnlockTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LevelUpUnlockTypeEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
