// <auto-generated>
// Generated from the client table LevelUpUnlock.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LevelUpUnlockEntry(uint ID, uint LevelUpUnlockSystemEnum, uint Level, uint LevelUpUnlockTypeId, uint LocalizedTextIdDescription, string DisplayIcon, uint PrerequisiteId, uint LevelUpUnlockValue);

public static class LevelUpUnlockTable
{
    public static IReadOnlyList<LevelUpUnlockEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LevelUpUnlockEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LevelUpUnlockEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
