// <auto-generated>
// Generated from the client table LiveEvent.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LiveEventEntry(uint ID, uint LiveEventTypeEnum, uint MaxValue, uint Flags, uint LiveEventCategoryEnum, uint LiveEventIdParent, uint LocalizedTextIdName, uint LocalizedTextIdSummary, string IconPath, string IconPathButton, string SpritePathTitle, string SpritePathBackground, uint CurrencyTypeIdEarned, uint LocalizedTextIdCurrencyEarnedTooltip, uint WorldLocation2IdExile, uint WorldLocation2IdDominion);

public static class LiveEventTable
{
    public static IReadOnlyList<LiveEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LiveEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LiveEventEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (string)row[8],
                (string)row[9],
                (string)row[10],
                (string)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15]
            ));
        return list;
    }
}
