// <auto-generated>
// Generated from the client table LiveEventDisplayItem.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LiveEventDisplayItemEntry(uint ID, uint LiveEventId, uint Item2Id, uint StoreLinkId);

public static class LiveEventDisplayItemTable
{
    public static IReadOnlyList<LiveEventDisplayItemEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LiveEventDisplayItemEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LiveEventDisplayItemEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
