// <auto-generated>
// Generated from the client table LocalizedText.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LocalizedTextEntry(uint ID, uint SoundEventId, uint SoundEventIdFemale, uint Version, uint UnitVoiceTypeId, uint StringContextEnum, uint SoundAvailabilityFlagFemale);

public static class LocalizedTextTable
{
    public static IReadOnlyList<LocalizedTextEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LocalizedTextEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LocalizedTextEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
