// <auto-generated>
// Generated from the client table LocalizedEnum.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LocalizedEnumEntry(uint ID, string EnumName, uint LocalizedTextId);

public static class LocalizedEnumTable
{
    public static IReadOnlyList<LocalizedEnumEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LocalizedEnumEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LocalizedEnumEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
