// <auto-generated>
// Generated from the client table LootSpell.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LootSpellEntry(uint ID, uint LootSpellTypeEnum, uint LootSpellPickupEnumFlags, uint Creature2Id, string ButtonIcon, uint LocalizedTextIdName, uint LocalizedTextIdDescription, uint VisualEffectId, uint Data, uint DataValue);

public static class LootSpellTable
{
    public static IReadOnlyList<LootSpellEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LootSpellEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LootSpellEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (string)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
