// <auto-generated>
// Generated from the client table LuaEvent.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record LuaEventEntry(uint ID, string EventName, string Parameters);

public static class LuaEventTable
{
    public static IReadOnlyList<LuaEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<LuaEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new LuaEventEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2]
            ));
        return list;
    }
}
