// <auto-generated>
// Generated from the client table MapContinent.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapContinentEntry(uint ID, uint LocalizedTextIdName, string AssetPath, string ImagePath, uint ImageWidth, uint ImageHeight, uint ImageOffsetX, uint ImageOffsetY, uint HexMinX, uint HexMinY, uint HexLimX, uint HexLimY, uint Flags);

public static class MapContinentTable
{
    public static IReadOnlyList<MapContinentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapContinentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapContinentEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
