// <auto-generated>
// Generated from the client table MapZoneWorldJoin.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneWorldJoinEntry(uint ID, uint MapZoneId, uint WorldId);

public static class MapZoneWorldJoinTable
{
    public static IReadOnlyList<MapZoneWorldJoinEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneWorldJoinEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneWorldJoinEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
