// <auto-generated>
// Generated from the client table MapZoneHexGroupEntry.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneHexGroupEntryEntry(uint ID, uint MapZoneHexGroupId, uint HexX, uint HexY);

public static class MapZoneHexGroupEntryTable
{
    public static IReadOnlyList<MapZoneHexGroupEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneHexGroupEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneHexGroupEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
