// <auto-generated>
// Generated from the client table MapZoneLevelBand.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneLevelBandEntry(uint ID, uint MapZoneHexGroupId, uint LevelMin, uint LevelMax, uint LabelX, uint LabelZ);

public static class MapZoneLevelBandTable
{
    public static IReadOnlyList<MapZoneLevelBandEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneLevelBandEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneLevelBandEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
