// <auto-generated>
// Generated from the client table MapZoneHex.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneHexEntry(uint ID, uint MapZoneId, uint Pos0, uint Pos1, uint Flags);

public static class MapZoneHexTable
{
    public static IReadOnlyList<MapZoneHexEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneHexEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneHexEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
