// <auto-generated>
// Generated from the client table MapZoneSprite.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneSpriteEntry(uint ID, string SpriteName);

public static class MapZoneSpriteTable
{
    public static IReadOnlyList<MapZoneSpriteEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneSpriteEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneSpriteEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
