// <auto-generated>
// Generated from the client table MapZoneHexGroup.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneHexGroupEntry(uint ID, uint MapZoneId);

public static class MapZoneHexGroupTable
{
    public static IReadOnlyList<MapZoneHexGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneHexGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneHexGroupEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
