// <auto-generated>
// Generated from the client table MapZone.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneEntry(uint ID, uint LocalizedTextIdName, uint MapContinentId, string Folder, uint HexMinX, uint HexMinY, uint HexLimX, uint HexLimY, uint Version, uint MapZoneIdParent, uint WorldZoneId, uint Flags, uint PrerequisiteIdVisibility, uint RewardTrackId);

public static class MapZoneTable
{
    public static IReadOnlyList<MapZoneEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
