// <auto-generated>
// Generated from the client table MapZoneNemesisRegion.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MapZoneNemesisRegionEntry(uint ID, uint MapZoneHexGroupId, uint LocalizedTextIdDescription, uint Faction2Id);

public static class MapZoneNemesisRegionTable
{
    public static IReadOnlyList<MapZoneNemesisRegionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MapZoneNemesisRegionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MapZoneNemesisRegionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
