// <auto-generated>
// Generated from the client table MatchingMapPrerequisite.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MatchingMapPrerequisiteEntry(uint ID, uint MatchingGameMapId, uint MatchingEligibilityFlagEnum);

public static class MatchingMapPrerequisiteTable
{
    public static IReadOnlyList<MatchingMapPrerequisiteEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MatchingMapPrerequisiteEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MatchingMapPrerequisiteEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
