// <auto-generated>
// Generated from the client table MatchTypeRewardRotationContent.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MatchTypeRewardRotationContentEntry(uint ID, uint MatchTypeEnum, uint RewardRotationContentIdRandomNormal, uint RewardRotationContentIdRandomVeteran);

public static class MatchTypeRewardRotationContentTable
{
    public static IReadOnlyList<MatchTypeRewardRotationContentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MatchTypeRewardRotationContentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MatchTypeRewardRotationContentEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
