// <auto-generated>
// Generated from the client table MatchingGameType.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MatchingGameTypeEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdDescription, uint MatchTypeEnum, uint MatchingGameTypeEnumFlags, uint TeamSize, uint MinLevel, uint MaxLevel, uint PreparationTimeMS, uint MatchTimeMS, uint MatchingRulesEnum, uint MatchingRulesData00, uint MatchingRulesData01, uint TargetItemLevel);

public static class MatchingGameTypeTable
{
    public static IReadOnlyList<MatchingGameTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MatchingGameTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MatchingGameTypeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
