// <auto-generated>
// Generated from the client table MatchingRandomReward.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MatchingRandomRewardEntry(uint ID, uint MatchTypeEnum, uint Item2Id, uint ItemCount, uint CurrencyTypeId, uint CurrencyValue, uint XpEarned, uint Item2IdLevelScale, uint ItemCountLevelScale, uint CurrencyTypeIdLevelScale, uint CurrencyValueLevelScale, uint XpEarnedLevelScale, uint WorldDifficultyEnum);

public static class MatchingRandomRewardTable
{
    public static IReadOnlyList<MatchingRandomRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MatchingRandomRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MatchingRandomRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
