// <auto-generated>
// Generated from the client table MaterialSet.tbl (1 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MaterialSetEntry(uint ID);

public static class MaterialSetTable
{
    public static IReadOnlyList<MaterialSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MaterialSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MaterialSetEntry(
                (uint)row[0]
            ));
        return list;
    }
}
