// <auto-generated>
// Generated from the client table MaterialType.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MaterialTypeEntry(uint ID, uint MaterialFlags);

public static class MaterialTypeTable
{
    public static IReadOnlyList<MaterialTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MaterialTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MaterialTypeEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
