// <auto-generated>
// Generated from the client table MaterialRemap.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MaterialRemapEntry(uint ID, uint MaterialDataRow, uint MaterialSetId, uint MaterialDataRowRemap);

public static class MaterialRemapTable
{
    public static IReadOnlyList<MaterialRemapEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MaterialRemapEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MaterialRemapEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
