// <auto-generated>
// Generated from the client table MaterialData.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MaterialDataEntry(uint ID, uint Row, uint MaterialTypeId);

public static class MaterialDataTable
{
    public static IReadOnlyList<MaterialDataEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MaterialDataEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MaterialDataEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
