// <auto-generated>
// Generated from the client table MiniMapMarker.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MiniMapMarkerEntry(uint ID, string LuaName);

public static class MiniMapMarkerTable
{
    public static IReadOnlyList<MiniMapMarkerEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MiniMapMarkerEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MiniMapMarkerEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
