// <auto-generated>
// Generated from the client table MissileRevolverTrack.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record MissileRevolverTrackEntry(uint ID, float Radius, float Speed, float SpeedMultiplier, float ScaleMultiplier, uint ModelAttachmentIdHeight);

public static class MissileRevolverTrackTable
{
    public static IReadOnlyList<MissileRevolverTrackEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<MissileRevolverTrackEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new MissileRevolverTrackEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
