// <auto-generated>
// Generated from the client table ModelMesh.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelMeshEntry(uint ID, string EnumName);

public static class ModelMeshTable
{
    public static IReadOnlyList<ModelMeshEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelMeshEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelMeshEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
