// <auto-generated>
// Generated from the client table ModelSequenceByMode.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSequenceByModeEntry(uint ID, uint ModelSequenceId, uint ModelSequenceIdSwim, uint ModelSequenceIdHover, uint ModelSequenceIdFly);

public static class ModelSequenceByModeTable
{
    public static IReadOnlyList<ModelSequenceByModeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSequenceByModeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSequenceByModeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
