// <auto-generated>
// Generated from the client table ModelEvent.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelEventEntry(uint ID, string EnumName);

public static class ModelEventTable
{
    public static IReadOnlyList<ModelEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelEventEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
