// <auto-generated>
// Generated from the client table ModelSequenceTransition.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSequenceTransitionEntry(uint ID, uint ModelSequenceIdFrom, uint ModelSequenceIdTo, uint ModelSequenceIdTransition);

public static class ModelSequenceTransitionTable
{
    public static IReadOnlyList<ModelSequenceTransitionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSequenceTransitionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSequenceTransitionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
