// <auto-generated>
// Generated from the client table ModelAttachment.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelAttachmentEntry(uint ID, string EnumName);

public static class ModelAttachmentTable
{
    public static IReadOnlyList<ModelAttachmentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelAttachmentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelAttachmentEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
