// <auto-generated>
// Generated from the client table ModelSequenceBySeatPosture.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSequenceBySeatPostureEntry(uint ID, uint ModelSequenceId, uint ModelSequenceIdNarrow, uint ModelSequenceIdMedium, uint ModelSequenceIdWide, uint ModelSequenceIdBike, uint ModelSequenceIdHoverBoard, uint ModelSequenceIdGlider, uint ModelSequenceIdTank);

public static class ModelSequenceBySeatPostureTable
{
    public static IReadOnlyList<ModelSequenceBySeatPostureEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSequenceBySeatPostureEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSequenceBySeatPostureEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
