// <auto-generated>
// Generated from the client table ModelPose.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelPoseEntry(uint ID, uint SequenceId, string Description, uint ModelPoseIdBase, uint ModelPoseTypeEnum);

public static class ModelPoseTable
{
    public static IReadOnlyList<ModelPoseEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelPoseEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelPoseEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
