// <auto-generated>
// Generated from the client table ModelCluster.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelClusterEntry(uint ID, string EnumName);

public static class ModelClusterTable
{
    public static IReadOnlyList<ModelClusterEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelClusterEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelClusterEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
