// <auto-generated>
// Generated from the client table ModelSequenceByWeapon.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSequenceByWeaponEntry(uint ID, uint ModelSequenceId, uint ModelSequenceId1H, uint ModelSequenceId2H, uint ModelSequenceId2HL, uint ModelSequenceId2HGun, uint ModelSequenceIdPistols, uint ModelSequenceIdClaws, uint ModelSequenceIdShockPaddles, uint ModelSequenceIdEsper, uint ModelSequenceIdPsyblade, uint ModelSequenceIdHeavygun);

public static class ModelSequenceByWeaponTable
{
    public static IReadOnlyList<ModelSequenceByWeaponEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSequenceByWeaponEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSequenceByWeaponEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
