// <auto-generated>
// Generated from the client table ModelBonePriority.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelBonePriorityEntry(uint ID, uint BoneID, uint BoneSetID, uint Priority);

public static class ModelBonePriorityTable
{
    public static IReadOnlyList<ModelBonePriorityEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelBonePriorityEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelBonePriorityEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
