// <auto-generated>
// Generated from the client table ModelEventVisualJoin.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelEventVisualJoinEntry(uint ID, uint UnitVisualTypeId, uint ItemVisualTypeId, uint MaterialTypeId, uint ModelEventId, uint VisualEffectId, uint ModelSequenceId, uint Flags);

public static class ModelEventVisualJoinTable
{
    public static IReadOnlyList<ModelEventVisualJoinEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelEventVisualJoinEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelEventVisualJoinEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
