// <auto-generated>
// Generated from the client table ModelSkinFX.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSkinFXEntry(uint ID, string Suffix);

public static class ModelSkinFXTable
{
    public static IReadOnlyList<ModelSkinFXEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSkinFXEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSkinFXEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
