// <auto-generated>
// Generated from the client table ModelBone.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelBoneEntry(uint ID, string XSIName);

public static class ModelBoneTable
{
    public static IReadOnlyList<ModelBoneEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelBoneEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelBoneEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
