// <auto-generated>
// Generated from the client table ModelCamera.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelCameraEntry(uint ID, string EnumName);

public static class ModelCameraTable
{
    public static IReadOnlyList<ModelCameraEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelCameraEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelCameraEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
