// <auto-generated>
// Generated from the client table ModelSequence.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelSequenceEntry(uint ID, string Description, uint FallBackID, uint Flag);

public static class ModelSequenceTable
{
    public static IReadOnlyList<ModelSequenceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelSequenceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelSequenceEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
