// <auto-generated>
// Generated from the client table ModelBoneSet.tbl (1 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ModelBoneSetEntry(uint ID);

public static class ModelBoneSetTable
{
    public static IReadOnlyList<ModelBoneSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ModelBoneSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ModelBoneSetEntry(
                (uint)row[0]
            ));
        return list;
    }
}
