// <auto-generated>
// Generated from the client table PathScientistSpecimenSurvey.tbl (41 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistSpecimenSurveyEntry(uint ID, uint LocalizedTextIdObjective00, uint LocalizedTextIdObjective01, uint LocalizedTextIdObjective02, uint LocalizedTextIdObjective03, uint LocalizedTextIdObjective04, uint LocalizedTextIdObjective05, uint LocalizedTextIdObjective06, uint LocalizedTextIdObjective07, uint LocalizedTextIdObjective08, uint LocalizedTextIdObjective09, uint WorldLocation2Id00, uint WorldLocation2Id01, uint WorldLocation2Id02, uint WorldLocation2Id03, uint WorldLocation2Id04, uint WorldLocation2Id05, uint WorldLocation2Id06, uint WorldLocation2Id07, uint WorldLocation2Id08, uint WorldLocation2Id09, uint SpecimenSurveyFlags00, uint SpecimenSurveyFlags01, uint SpecimenSurveyFlags02, uint SpecimenSurveyFlags03, uint SpecimenSurveyFlags04, uint SpecimenSurveyFlags05, uint SpecimenSurveyFlags06, uint SpecimenSurveyFlags07, uint SpecimenSurveyFlags08, uint SpecimenSurveyFlags09, uint QuestDirectionId00, uint QuestDirectionId01, uint QuestDirectionId02, uint QuestDirectionId03, uint QuestDirectionId04, uint QuestDirectionId05, uint QuestDirectionId06, uint QuestDirectionId07, uint QuestDirectionId08, uint QuestDirectionId09);

public static class PathScientistSpecimenSurveyTable
{
    public static IReadOnlyList<PathScientistSpecimenSurveyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistSpecimenSurveyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistSpecimenSurveyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40]
            ));
        return list;
    }
}
