// <auto-generated>
// Generated from the client table PathEpisode.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathEpisodeEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdSummary, uint WorldId, uint WorldZoneId, uint PathTypeEnum);

public static class PathEpisodeTable
{
    public static IReadOnlyList<PathEpisodeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathEpisodeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathEpisodeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
