// <auto-generated>
// Generated from the client table PathScientistExperimentationPattern.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistExperimentationPatternEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdDescription, uint PathMissionId, uint PathScientistExperimentationId, string IconAssetPath);

public static class PathScientistExperimentationPatternTable
{
    public static IReadOnlyList<PathScientistExperimentationPatternEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistExperimentationPatternEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistExperimentationPatternEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5]
            ));
        return list;
    }
}
