// <auto-generated>
// Generated from the client table PathExplorerScavengerClue.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathExplorerScavengerClueEntry(uint ID, uint LocalizedTextIdClue, uint ExplorerScavengerClueTypeEnum, uint Creature2Id, uint TargetGroupId, float ActiveRadius, uint WorldLocation2IdMiniMap);

public static class PathExplorerScavengerClueTable
{
    public static IReadOnlyList<PathExplorerScavengerClueEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathExplorerScavengerClueEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathExplorerScavengerClueEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (float)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
