// <auto-generated>
// Generated from the client table PathExplorerPowerMap.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathExplorerPowerMapEntry(uint ID, uint DistanceThreshold, uint CollectQuantity, uint VictoryPauseMS, uint WorldLocation2IdVisual, uint VisualEffectIdInactive, uint LocalizedTextIdInfo);

public static class PathExplorerPowerMapTable
{
    public static IReadOnlyList<PathExplorerPowerMapEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathExplorerPowerMapEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathExplorerPowerMapEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
