// <auto-generated>
// Generated from the client table PathSoldierEventWave.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSoldierEventWaveEntry(uint ID, uint PathSoldierEventId, uint WaveIndex, uint SoundZoneKitId);

public static class PathSoldierEventWaveTable
{
    public static IReadOnlyList<PathSoldierEventWaveEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSoldierEventWaveEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSoldierEventWaveEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
