// <auto-generated>
// Generated from the client table PathSettlerImprovementGroup.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSettlerImprovementGroupEntry(uint ID, uint PathSettlerHubId, uint PathSettlerImprovementGroupFlags, uint Creature2IdDepot, uint LocalizedTextIdName, uint SettlerAvenueTypeEnum, uint ContributionValue, uint PerTierBonusContributionValue, uint DurationPerBundleMs, uint MaxBundleCount, uint PathSettlerImprovementGroupIdOutpostRequired, uint PathSettlerImprovementIdTier00, uint PathSettlerImprovementIdTier01, uint PathSettlerImprovementIdTier02, uint PathSettlerImprovementIdTier03, uint WorldLocation2IdDisplayPoint);

public static class PathSettlerImprovementGroupTable
{
    public static IReadOnlyList<PathSettlerImprovementGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSettlerImprovementGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSettlerImprovementGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15]
            ));
        return list;
    }
}
