// <auto-generated>
// Generated from the client table PathSoldierSWAT.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSoldierSWATEntry(uint ID, uint Creature2Id, uint TargetGroupId, uint Count, uint VirtualItemIdDisplay);

public static class PathSoldierSWATTable
{
    public static IReadOnlyList<PathSoldierSWATEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSoldierSWATEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSoldierSWATEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
