// <auto-generated>
// Generated from the client table PathScientistCreatureInfo.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistCreatureInfoEntry(uint ID, uint ScientistCreatureFlags, string DisplayIcon, uint PrerequisiteIdScan, uint PrerequisiteIdRawScan, uint PrerequisiteIdScanCreature, uint PrerequisiteIdRawScanCreature, uint Spell4IdBuff00, uint Spell4IdBuff01, uint Spell4IdBuff02, uint Spell4IdBuff03, uint ChecklistCount, uint ScientistCreatureTypeEnum, uint LootId);

public static class PathScientistCreatureInfoTable
{
    public static IReadOnlyList<PathScientistCreatureInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistCreatureInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistCreatureInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
