// <auto-generated>
// Generated from the client table PathLevel.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathLevelEntry(uint ID, uint PathTypeEnum, uint PathLevel, uint PathXP);

public static class PathLevelTable
{
    public static IReadOnlyList<PathLevelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathLevelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathLevelEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
