// <auto-generated>
// Generated from the client table PathExplorerActivate.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathExplorerActivateEntry(uint ID, uint Creature2Id, uint TargetGroupId, uint Count);

public static class PathExplorerActivateTable
{
    public static IReadOnlyList<PathExplorerActivateEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathExplorerActivateEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathExplorerActivateEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
