// <auto-generated>
// Generated from the client table PathSettlerMayor.tbl (26 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSettlerMayorEntry(uint ID, uint LocalizedTextId00, uint LocalizedTextId01, uint LocalizedTextId02, uint LocalizedTextId03, uint LocalizedTextId04, uint LocalizedTextId05, uint LocalizedTextId06, uint LocalizedTextId07, uint WorldLocation2Id00, uint WorldLocation2Id01, uint WorldLocation2Id02, uint WorldLocation2Id03, uint WorldLocation2Id04, uint WorldLocation2Id05, uint WorldLocation2Id06, uint WorldLocation2Id07, uint QuestDirectionId00, uint QuestDirectionId01, uint QuestDirectionId02, uint QuestDirectionId03, uint QuestDirectionId04, uint QuestDirectionId05, uint QuestDirectionId06, uint QuestDirectionId07, uint CharacterTitleIdReward);

public static class PathSettlerMayorTable
{
    public static IReadOnlyList<PathSettlerMayorEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSettlerMayorEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSettlerMayorEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25]
            ));
        return list;
    }
}
