// <auto-generated>
// Generated from the client table PathSoldierAssassinate.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSoldierAssassinateEntry(uint ID, uint Creature2Id, uint TargetGroupId, uint Count);

public static class PathSoldierAssassinateTable
{
    public static IReadOnlyList<PathSoldierAssassinateEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSoldierAssassinateEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSoldierAssassinateEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
