// <auto-generated>
// Generated from the client table PathExplorerDoor.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathExplorerDoorEntry(uint ID, uint WorldZoneIdInsideMicro, uint TargetGroupIdActivate, uint TargetGroupIdKill);

public static class PathExplorerDoorTable
{
    public static IReadOnlyList<PathExplorerDoorEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathExplorerDoorEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathExplorerDoorEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
