// <auto-generated>
// Generated from the client table PathReward.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathRewardEntry(uint ID, uint PathRewardTypeEnum, uint ObjectId, uint Spell4Id, uint Item2Id, uint Quest2Id, uint CharacterTitleId, uint PrerequisiteId, uint Count, uint PathRewardFlags, uint PathScientistScanBotProfileId);

public static class PathRewardTable
{
    public static IReadOnlyList<PathRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
