// <auto-generated>
// Generated from the client table PathScientistExperimentation.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistExperimentationEntry(uint ID, uint NumAttempts);

public static class PathScientistExperimentationTable
{
    public static IReadOnlyList<PathScientistExperimentationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistExperimentationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistExperimentationEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
