// <auto-generated>
// Generated from the client table PathSoldierEvent.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSoldierEventEntry(uint ID, uint PathSoldierEventType, uint MaxTimeBetweenWaves, uint MaxEventTime, uint TowerDefenseAllowance, uint TowerDefenseBuildTimeMS, uint InitialSpawnTime);

public static class PathSoldierEventTable
{
    public static IReadOnlyList<PathSoldierEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSoldierEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSoldierEventEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
