// <auto-generated>
// Generated from the client table PathMission.tbl (21 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathMissionEntry(uint ID, uint Creature2IdUnlock, uint PathTypeEnum, uint PathMissionTypeEnum, uint PathMissionDisplayTypeEnum, uint ObjectId, uint LocalizedTextIdName, uint LocalizedTextIdSummary, uint PathEpisodeId, uint WorldLocation2Id00, uint WorldLocation2Id01, uint WorldLocation2Id02, uint WorldLocation2Id03, uint PathMissionFlags, uint PathMissionFactionEnum, uint PrerequisiteId, uint LocalizedTextIdCommunicator, uint LocalizedTextIdUnlock, uint LocalizedTextIdSoldierOrders, uint Creature2IdContactOverride, uint QuestDirectionId);

public static class PathMissionTable
{
    public static IReadOnlyList<PathMissionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathMissionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathMissionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20]
            ));
        return list;
    }
}
