// <auto-generated>
// Generated from the client table PathScientistDatacubeDiscovery.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistDatacubeDiscoveryEntry(uint ID, uint WorldZoneId);

public static class PathScientistDatacubeDiscoveryTable
{
    public static IReadOnlyList<PathScientistDatacubeDiscoveryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistDatacubeDiscoveryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistDatacubeDiscoveryEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
