// <auto-generated>
// Generated from the client table PathScientistFieldStudy.tbl (28 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistFieldStudyEntry(uint ID, uint Creature2Id, uint TargetGroupId, uint PathScientistFieldStudyFlags, uint LocalizedTextIdChecklist00, uint LocalizedTextIdChecklist01, uint LocalizedTextIdChecklist02, uint LocalizedTextIdChecklist03, uint LocalizedTextIdChecklist04, uint LocalizedTextIdChecklist05, uint LocalizedTextIdChecklist06, uint LocalizedTextIdChecklist07, uint WorldLocation2IdIndicator00, uint WorldLocation2IdIndicator01, uint WorldLocation2IdIndicator02, uint WorldLocation2IdIndicator03, uint WorldLocation2IdIndicator04, uint WorldLocation2IdIndicator05, uint WorldLocation2IdIndicator06, uint WorldLocation2IdIndicator07, uint BehaviorType00, uint BehaviorType01, uint BehaviorType02, uint BehaviorType03, uint BehaviorType04, uint BehaviorType05, uint BehaviorType06, uint BehaviorType07);

public static class PathScientistFieldStudyTable
{
    public static IReadOnlyList<PathScientistFieldStudyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistFieldStudyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistFieldStudyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27]
            ));
        return list;
    }
}
