// <auto-generated>
// Generated from the client table PathSettlerSheriff.tbl (18 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSettlerSheriffEntry(uint ID, uint Quest2IdSheriff00, uint Quest2IdSheriff01, uint Quest2IdSheriff02, uint Quest2IdSheriff03, uint Quest2IdSheriff04, uint Quest2IdSheriff05, uint Quest2IdSheriff06, uint Quest2IdSheriff07, uint LocalizedTextIdDescription00, uint LocalizedTextIdDescription01, uint LocalizedTextIdDescription02, uint LocalizedTextIdDescription03, uint LocalizedTextIdDescription04, uint LocalizedTextIdDescription05, uint LocalizedTextIdDescription06, uint LocalizedTextIdDescription07, uint CharacterTitleIdReward);

public static class PathSettlerSheriffTable
{
    public static IReadOnlyList<PathSettlerSheriffEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSettlerSheriffEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSettlerSheriffEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17]
            ));
        return list;
    }
}
