// <auto-generated>
// Generated from the client table PathSettlerHub.tbl (29 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSettlerHubEntry(uint ID, uint MaxAvenueEconomy, uint MaxAvenueSecurity, uint MaxAvenueQualityOfLife, uint LocalizedTextIdEconomy, uint LocalizedTextIdSecurity, uint LocalizedTextIdQualityOfLife, uint WorldZoneId, uint MissionCount, uint Flags, uint Item2IdResource00, uint Item2IdResource01, uint Item2IdResource02, uint PublicEventObjectiveIdResource00, uint PublicEventObjectiveIdResource01, uint PublicEventObjectiveIdResource02, uint WorldLocation2IdMapResource00Loc00, uint WorldLocation2IdMapResource00Loc01, uint WorldLocation2IdMapResource00Loc02, uint WorldLocation2IdMapResource00Loc03, uint WorldLocation2IdMapResource01Loc00, uint WorldLocation2IdMapResource01Loc01, uint WorldLocation2IdMapResource01Loc02, uint WorldLocation2IdMapResource01Loc03, uint WorldLocation2IdMapResource02Loc00, uint WorldLocation2IdMapResource02Loc01, uint WorldLocation2IdMapResource02Loc02, uint WorldLocation2IdMapResource02Loc03, uint LocalizedTextIdRewardNotify);

public static class PathSettlerHubTable
{
    public static IReadOnlyList<PathSettlerHubEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSettlerHubEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSettlerHubEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28]
            ));
        return list;
    }
}
