// <auto-generated>
// Generated from the client table PathScientistScanBotProfile.tbl (17 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathScientistScanBotProfileEntry(uint ID, uint LocalizedTextId, uint Creature2Id, uint ScanTimeMS, uint ProcessingTimeMS, float PlayerRadius, float ScanAOERange, float MaxSeekDistance, float SpeedMultiplier, float ThoroughnessMultiplier, float HealthMultiplier, float HealthRegenMultiplier, uint MinCooldownTimeMs, uint MaxCooldownTimeMs, float MaxCooldownDistance, uint PathScientistScanBotProfileFlags, uint SocketCount);

public static class PathScientistScanBotProfileTable
{
    public static IReadOnlyList<PathScientistScanBotProfileEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathScientistScanBotProfileEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathScientistScanBotProfileEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (uint)row[12],
                (uint)row[13],
                (float)row[14],
                (uint)row[15],
                (uint)row[16]
            ));
        return list;
    }
}
