// <auto-generated>
// Generated from the client table PathSettlerInfrastructure.tbl (18 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSettlerInfrastructureEntry(uint ID, uint PathSettlerHubId00, uint PathSettlerHubId01, uint LocalizedTextIdObjective, uint MissionCount, uint WorldZoneId, uint Count, uint MaxTime, uint Creature2IdDepot, uint Creature2IdResource00, uint Creature2IdResource01, uint Creature2IdResource02, uint Spell4IdResource00, uint Spell4IdResource01, uint Spell4IdResource02, uint MaxStackCountResource00, uint MaxStackCountResource01, uint MaxStackCountResource02);

public static class PathSettlerInfrastructureTable
{
    public static IReadOnlyList<PathSettlerInfrastructureEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSettlerInfrastructureEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSettlerInfrastructureEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17]
            ));
        return list;
    }
}
