// <auto-generated>
// Generated from the client table PathExplorerScavengerHunt.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathExplorerScavengerHuntEntry(uint ID, uint Creature2IdStart, uint PathExplorerScavengerClueId00, uint PathExplorerScavengerClueId01, uint PathExplorerScavengerClueId02, uint PathExplorerScavengerClueId03, uint PathExplorerScavengerClueId04, uint PathExplorerScavengerClueId05, uint PathExplorerScavengerClueId06, uint LocalizedTextIdStart, uint Spell4IdRelic, string AssetPathSprite);

public static class PathExplorerScavengerHuntTable
{
    public static IReadOnlyList<PathExplorerScavengerHuntEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathExplorerScavengerHuntEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathExplorerScavengerHuntEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (string)row[11]
            ));
        return list;
    }
}
