// <auto-generated>
// Generated from the client table PathSoldierTowerDefense.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PathSoldierTowerDefenseEntry(uint ID, uint PathSoldierEventId, uint BuildCost, uint LocalizedTextIdName, uint WorldLocation2IdDisplay, uint TowerDefenseBuildType, uint Spell4Id, uint SoldierTowerDefenseFlags, uint SoldierTowerDefenseImprovementType);

public static class PathSoldierTowerDefenseTable
{
    public static IReadOnlyList<PathSoldierTowerDefenseEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PathSoldierTowerDefenseEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PathSoldierTowerDefenseEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
