// <auto-generated>
// Generated from the client table PeriodicQuestGroup.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PeriodicQuestGroupEntry(uint ID, uint PeriodicQuestSetId, uint PeriodicQuestsOffered, uint MaxPeriodicQuestsAllowed, uint Weight, uint ContractTypeEnum, uint ContractQualityEnum);

public static class PeriodicQuestGroupTable
{
    public static IReadOnlyList<PeriodicQuestGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PeriodicQuestGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PeriodicQuestGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
