// <auto-generated>
// Generated from the client table PeriodicQuestSetCategory.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PeriodicQuestSetCategoryEntry(uint ID, uint PeriodicSetsOffered);

public static class PeriodicQuestSetCategoryTable
{
    public static IReadOnlyList<PeriodicQuestSetCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PeriodicQuestSetCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PeriodicQuestSetCategoryEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
