// <auto-generated>
// Generated from the client table PetFlair.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PetFlairEntry(uint ID, uint UnlockBitIndex00, uint UnlockBitIndex01, uint Type, uint Spell4Id, uint LocalizedTextIdTooltip, uint ItemDisplayId00, uint ItemDisplayId01, uint PrerequisiteId);

public static class PetFlairTable
{
    public static IReadOnlyList<PetFlairEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PetFlairEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PetFlairEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
