// <auto-generated>
// Generated from the client table PositionalRequirement.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PositionalRequirementEntry(uint ID, uint AngleCenter, uint AngleRange, uint Flags);

public static class PositionalRequirementTable
{
    public static IReadOnlyList<PositionalRequirementEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PositionalRequirementEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PositionalRequirementEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
