// <auto-generated>
// Generated from the client table PrerequisiteType.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PrerequisiteTypeEntry(uint ID, uint LocalizedTextIdError);

public static class PrerequisiteTypeTable
{
    public static IReadOnlyList<PrerequisiteTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PrerequisiteTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PrerequisiteTypeEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
