// <auto-generated>
// Generated from the client table Prerequisite.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PrerequisiteEntry(uint ID, uint Flags, uint PrerequisiteTypeId0, uint PrerequisiteTypeId1, uint PrerequisiteTypeId2, uint PrerequisiteComparisonId0, uint PrerequisiteComparisonId1, uint PrerequisiteComparisonId2, uint ObjectId0, uint ObjectId1, uint ObjectId2, uint Value0, uint Value1, uint Value2, uint LocalizedTextIdFailure);

public static class PrerequisiteTable
{
    public static IReadOnlyList<PrerequisiteEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PrerequisiteEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PrerequisiteEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14]
            ));
        return list;
    }
}
