// <auto-generated>
// Generated from the client table PrimalMatrixReward.tbl (17 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PrimalMatrixRewardEntry(uint ID, uint PrimalMatrixRewardTypeEnum0, uint PrimalMatrixRewardTypeEnum1, uint PrimalMatrixRewardTypeEnum2, uint PrimalMatrixRewardTypeEnum3, uint ObjectId0, uint ObjectId1, uint ObjectId2, uint ObjectId3, uint SubObjectId0, uint SubObjectId1, uint SubObjectId2, uint SubObjectId3, float Value0, float Value1, float Value2, float Value3);

public static class PrimalMatrixRewardTable
{
    public static IReadOnlyList<PrimalMatrixRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PrimalMatrixRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PrimalMatrixRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16]
            ));
        return list;
    }
}
