// <auto-generated>
// Generated from the client table PrimalMatrixNode.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PrimalMatrixNodeEntry(uint ID, uint PositionX, uint PositionY, uint PrimalMatrixNodeTypeEnum, uint Flags, uint MaxAllocations, uint CostRedEssence, uint CostBlueEssence, uint CostGreenEssence, uint CostPurpleEssence, uint PrimalMatrixRewardIdWarrior, uint PrimalMatrixRewardIdEngineer, uint PrimalMatrixRewardIdEsper, uint PrimalMatrixRewardIdMedic, uint PrimalMatrixRewardIdStalker, uint PrimalMatrixRewardIdSpellslinger);

public static class PrimalMatrixNodeTable
{
    public static IReadOnlyList<PrimalMatrixNodeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PrimalMatrixNodeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PrimalMatrixNodeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15]
            ));
        return list;
    }
}
