// <auto-generated>
// Generated from the client table PropAdditionalDetail.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PropAdditionalDetailEntry(uint ID, uint LocalizedTextId);

public static class PropAdditionalDetailTable
{
    public static IReadOnlyList<PropAdditionalDetailEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PropAdditionalDetailEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PropAdditionalDetailEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
