// <auto-generated>
// Generated from the client table PublicEventVote.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventVoteEntry(uint ID, uint LocalizedTextIdTitle, uint LocalizedTextIdDescription, uint LocalizedTextIdOption00, uint LocalizedTextIdOption01, uint LocalizedTextIdOption02, uint LocalizedTextIdOption03, uint LocalizedTextIdOption04, uint LocalizedTextIdLabel00, uint LocalizedTextIdLabel01, uint LocalizedTextIdLabel02, uint LocalizedTextIdLabel03, uint LocalizedTextIdLabel04, uint DurationMS, string AssetPathSprite);

public static class PublicEventVoteTable
{
    public static IReadOnlyList<PublicEventVoteEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventVoteEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventVoteEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (string)row[14]
            ));
        return list;
    }
}
