// <auto-generated>
// Generated from the client table PublicEventRewardModifier.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventRewardModifierEntry(uint ID, uint PublicEventId, uint RewardPropertyId, uint Data, float Offset);

public static class PublicEventRewardModifierTable
{
    public static IReadOnlyList<PublicEventRewardModifierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventRewardModifierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventRewardModifierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (float)row[4]
            ));
        return list;
    }
}
