// <auto-generated>
// Generated from the client table PublicEventVirtualItemDepot.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventVirtualItemDepotEntry(uint ID, uint Creature2Id, uint VirtualItemId00, uint VirtualItemId01, uint VirtualItemId02, uint VirtualItemId03, uint VirtualItemId04, uint VirtualItemId05);

public static class PublicEventVirtualItemDepotTable
{
    public static IReadOnlyList<PublicEventVirtualItemDepotEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventVirtualItemDepotEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventVirtualItemDepotEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
