// <auto-generated>
// Generated from the client table PublicEventObjectiveGatherResource.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventObjectiveGatherResourceEntry(uint ID, uint PublicEventObjectiveGatherResourceEnumFlag, uint Creature2IdContainer, uint Creature2IdResource, uint Spell4IdResource, uint Creature2IdStolenResource, uint Spell4IdStolenResource, uint PublicEventObjectiveGatherResourceIdOpposing);

public static class PublicEventObjectiveGatherResourceTable
{
    public static IReadOnlyList<PublicEventObjectiveGatherResourceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventObjectiveGatherResourceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventObjectiveGatherResourceEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
