// <auto-generated>
// Generated from the client table PublicEventUnitPropertyModifier.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventUnitPropertyModifierEntry(uint ID, uint PublicEventId, uint UnitProperty2Id, float Scalar);

public static class PublicEventUnitPropertyModifierTable
{
    public static IReadOnlyList<PublicEventUnitPropertyModifierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventUnitPropertyModifierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventUnitPropertyModifierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3]
            ));
        return list;
    }
}
