// <auto-generated>
// Generated from the client table PublicEventObjectiveBombDeployment.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventObjectiveBombDeploymentEntry(uint ID, uint Creature2IdBomb, uint Spell4IdCarrying);

public static class PublicEventObjectiveBombDeploymentTable
{
    public static IReadOnlyList<PublicEventObjectiveBombDeploymentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventObjectiveBombDeploymentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventObjectiveBombDeploymentEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
