// <auto-generated>
// Generated from the client table PublicEvent.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventEntry(uint ID, uint WorldId, uint WorldZoneId, uint LocalizedTextIdName, uint FailureTimeMs, uint WorldLocation2Id, uint PublicEventTypeEnum, uint PublicEventIdParent, uint MinPlayerLevel, uint LiveEventIdLifetime, uint PublicEventFlags, uint LocalizedTextIdEnd, uint RewardRotationContentId);

public static class PublicEventTable
{
    public static IReadOnlyList<PublicEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
