// <auto-generated>
// Generated from the client table PublicEventObjectiveState.tbl (17 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventObjectiveStateEntry(uint ID, uint LocalizedTextIdState00, uint LocalizedTextIdState01, uint LocalizedTextIdState02, uint LocalizedTextIdState03, uint LocalizedTextIdState04, uint LocalizedTextIdState05, uint LocalizedTextIdState06, uint LocalizedTextIdState07, uint LocalizedTextIdState08, uint LocalizedTextIdState09, uint LocalizedTextIdState10, uint LocalizedTextIdState11, uint LocalizedTextIdState12, uint LocalizedTextIdState13, uint LocalizedTextIdState14, uint LocalizedTextIdState15);

public static class PublicEventObjectiveStateTable
{
    public static IReadOnlyList<PublicEventObjectiveStateEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventObjectiveStateEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventObjectiveStateEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16]
            ));
        return list;
    }
}
