// <auto-generated>
// Generated from the client table PublicEventStatDisplay.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventStatDisplayEntry(uint ID, uint PublicEventTypeEnum, uint PublicEventId, uint Flags);

public static class PublicEventStatDisplayTable
{
    public static IReadOnlyList<PublicEventStatDisplayEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventStatDisplayEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventStatDisplayEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
