// <auto-generated>
// Generated from the client table PublicEventObjective.tbl (23 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventObjectiveEntry(uint ID, uint PublicEventId, uint PublicEventObjectiveFlags, uint PublicEventObjectiveTypeSpecificFlags, uint WorldLocation2Id, uint PublicEventTeamId, uint LocalizedTextId, uint LocalizedTextIdOtherTeam, uint LocalizedTextIdShort, uint LocalizedTextIdOtherTeamShort, uint PublicEventObjectiveTypeEnum, uint Count, uint ObjectId, uint FailureTimeMs, uint TargetGroupIdRewardPane, uint PublicEventObjectiveCategoryEnum, uint LiveEventIdCounter, uint PublicEventObjectiveIdParent, uint QuestDirectionId, uint MedalPointValue, uint LocalizedTextIdParticipantAdd, uint LocalizedTextIdStart, uint DisplayOrder);

public static class PublicEventObjectiveTable
{
    public static IReadOnlyList<PublicEventObjectiveEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventObjectiveEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventObjectiveEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22]
            ));
        return list;
    }
}
