// <auto-generated>
// Generated from the client table PublicEventCustomStat.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PublicEventCustomStatEntry(uint ID, uint PublicEventTypeEnum, uint PublicEventId, uint StatIndex, uint LocalizedTextIdStatName, string IconPath);

public static class PublicEventCustomStatTable
{
    public static IReadOnlyList<PublicEventCustomStatEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PublicEventCustomStatEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PublicEventCustomStatEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5]
            ));
        return list;
    }
}
