// <auto-generated>
// Generated from the client table PvPRatingFloor.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record PvPRatingFloorEntry(uint ID, uint Flags, uint PvpRatingTypeEnum, uint FloorValue, uint LocalizedTextIdLabel);

public static class PvPRatingFloorTable
{
    public static IReadOnlyList<PvPRatingFloorEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<PvPRatingFloorEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new PvPRatingFloorEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
