// <auto-generated>
// Generated from the client table QuestObjective.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record QuestObjectiveEntry(uint ID, uint Type, uint Flags, uint Data, uint Count, uint LocalizedTextIdFull, uint WorldLocationsIdIndicator00, uint WorldLocationsIdIndicator01, uint WorldLocationsIdIndicator02, uint WorldLocationsIdIndicator03, uint MaxTimeAllowedMS, uint LocalizedTextIdShort, uint TargetGroupIdRewardPane, uint QuestDirectionId);

public static class QuestObjectiveTable
{
    public static IReadOnlyList<QuestObjectiveEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<QuestObjectiveEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new QuestObjectiveEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
