// <auto-generated>
// Generated from the client table QuestCategory.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record QuestCategoryEntry(uint ID, string Description, uint LocalizedTextIdTitle, uint QuestCategoryTypeEnum);

public static class QuestCategoryTable
{
    public static IReadOnlyList<QuestCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<QuestCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new QuestCategoryEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
