// <auto-generated>
// Generated from the client table QuestDirection.tbl (19 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record QuestDirectionEntry(uint ID, uint QuestDirectionFlags, uint QuestDirectionEntryId00, uint QuestDirectionEntryId01, uint QuestDirectionEntryId02, uint QuestDirectionEntryId03, uint QuestDirectionEntryId04, uint QuestDirectionEntryId05, uint QuestDirectionEntryId06, uint QuestDirectionEntryId07, uint QuestDirectionEntryId08, uint QuestDirectionEntryId09, uint QuestDirectionEntryId10, uint QuestDirectionEntryId11, uint QuestDirectionEntryId12, uint QuestDirectionEntryId13, uint QuestDirectionEntryId14, uint QuestDirectionEntryId15, uint WorldZoneIdExcludedZone);

public static class QuestDirectionTable
{
    public static IReadOnlyList<QuestDirectionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<QuestDirectionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new QuestDirectionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18]
            ));
        return list;
    }
}
