// <auto-generated>
// Generated from the client table QuestDirectionEntry.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record QuestDirectionEntryEntry(uint ID, uint WorldLocation2Id, uint WorldLocation2IdInactive, uint WorldZoneId, uint QuestDirectionEntryFlags, uint QuestDirectionFactionEnum);

public static class QuestDirectionEntryTable
{
    public static IReadOnlyList<QuestDirectionEntryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<QuestDirectionEntryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new QuestDirectionEntryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
