// <auto-generated>
// Generated from the client table QuestHub.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record QuestHubEntry(uint ID, uint WorldLocation2Id, uint LocalizedTextIdName);

public static class QuestHubTable
{
    public static IReadOnlyList<QuestHubEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<QuestHubEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new QuestHubEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
