// <auto-generated>
// Generated from the client table Quest2Difficulty.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Quest2DifficultyEntry(uint ID, float XpMultiplier, float CashRewardMultiplier, float RepRewardMultiplier);

public static class Quest2DifficultyTable
{
    public static IReadOnlyList<Quest2DifficultyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Quest2DifficultyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Quest2DifficultyEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3]
            ));
        return list;
    }
}
