// <auto-generated>
// Generated from the client table Quest2Reward.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Quest2RewardEntry(uint ID, uint Quest2Id, uint Quest2RewardTypeId, uint ObjectId, uint ObjectAmount, uint Flags);

public static class Quest2RewardTable
{
    public static IReadOnlyList<Quest2RewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Quest2RewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Quest2RewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
