// <auto-generated>
// Generated from the client table Race.tbl (31 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RaceEntry(uint ID, string EnumName, uint LocalizedTextId, uint LocalizedTextIdNameFemale, string MaleAssetPath, string FemaleAssetPath, float HitRadius, uint SoundImpactDescriptionIdOrigin, uint SoundImpactDescriptionIdTarget, float WalkLand, float WalkAir, float WalkWater, float WalkHover, uint UnitVisualTypeIdMale, uint UnitVisualTypeIdFemale, uint SoundEventIdMaleHealthStart, uint SoundEventIdFemaleHealthStart, uint SoundEventIdMaleHealthStop, uint SoundEventIdFemaleHealthStop, float SwimWaterDepth, uint ItemDisplayIdUnderwearLegsMale, uint ItemDisplayIdUnderwearLegsFemale, uint ItemDisplayIdUnderwearChestFemale, uint ItemDisplayIdArmCannon, float MountScaleMale, float MountScaleFemale, uint SoundSwitchId, uint ComponentLayoutIdMale, uint ComponentLayoutIdFemale, uint ModelMeshIdMountItemMale, uint ModelMeshIdMountItemFemale);

public static class RaceTable
{
    public static IReadOnlyList<RaceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RaceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RaceEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (string)row[4],
                (string)row[5],
                (float)row[6],
                (uint)row[7],
                (uint)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (float)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (float)row[24],
                (float)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30]
            ));
        return list;
    }
}
