// <auto-generated>
// Generated from the client table RandomTextLineSet.tbl (46 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RandomTextLineSetEntry(uint ID, uint GeneralVOSetEnumFirst00, uint GeneralVOSetEnumFirst01, uint GeneralVOSetEnumFirst02, uint GeneralVOSetEnumFirst03, uint GeneralVOSetEnumFirst04, uint GeneralVOSetEnumFirst05, uint GeneralVOSetEnumFirst06, uint GeneralVOSetEnumFirst07, uint GeneralVOSetEnumFirst08, uint GeneralVOSetEnumFirst09, uint GeneralVOSetEnumFirst10, uint GeneralVOSetEnumFirst11, uint GeneralVOSetEnumFirst12, uint GeneralVOSetEnumFirst13, uint GeneralVOSetEnumFirst14, uint GeneralVOSetEnumSecond00, uint GeneralVOSetEnumSecond01, uint GeneralVOSetEnumSecond02, uint GeneralVOSetEnumSecond03, uint GeneralVOSetEnumSecond04, uint GeneralVOSetEnumSecond05, uint GeneralVOSetEnumSecond06, uint GeneralVOSetEnumSecond07, uint GeneralVOSetEnumSecond08, uint GeneralVOSetEnumSecond09, uint GeneralVOSetEnumSecond10, uint GeneralVOSetEnumSecond11, uint GeneralVOSetEnumSecond12, uint GeneralVOSetEnumSecond13, uint GeneralVOSetEnumSecond14, uint LocalizedTextId00, uint LocalizedTextId01, uint LocalizedTextId02, uint LocalizedTextId03, uint LocalizedTextId04, uint LocalizedTextId05, uint LocalizedTextId06, uint LocalizedTextId07, uint LocalizedTextId08, uint LocalizedTextId09, uint LocalizedTextId10, uint LocalizedTextId11, uint LocalizedTextId12, uint LocalizedTextId13, uint LocalizedTextId14);

public static class RandomTextLineSetTable
{
    public static IReadOnlyList<RandomTextLineSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RandomTextLineSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RandomTextLineSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37],
                (uint)row[38],
                (uint)row[39],
                (uint)row[40],
                (uint)row[41],
                (uint)row[42],
                (uint)row[43],
                (uint)row[44],
                (uint)row[45]
            ));
        return list;
    }
}
