// <auto-generated>
// Generated from the client table RandomPlayerName.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RandomPlayerNameEntry(uint ID, string NameFragment, uint NameFragmentTypeEnum, uint RaceId, uint Gender, uint Faction2Id, uint LanguageFlags);

public static class RandomPlayerNameTable
{
    public static IReadOnlyList<RandomPlayerNameEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RandomPlayerNameEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RandomPlayerNameEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
