// <auto-generated>
// Generated from the client table RandomTextLine.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RandomTextLineEntry(uint ID, uint LocalizedTextId, uint RandomTextLineSetId);

public static class RandomTextLineTable
{
    public static IReadOnlyList<RandomTextLineEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RandomTextLineEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RandomTextLineEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
