// <auto-generated>
// Generated from the client table RealmDataCenter.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RealmDataCenterEntry(uint ID, uint Flags, uint DeploymentRegionEnum, uint DeploymentTypeEnum, uint LocalizedTextId, string AuthServer, string NcClientAuthServer, string NcRedirectUrlTemplate, string NcRedirectUrlTemplateSignature, string NcAppGroupCode, uint NcProgramAuth, string SteamSignatureUrlTemplate, string SteamNCoinUrlTemplate, string StoreBannerDataUrlTemplate);

public static class RealmDataCenterTable
{
    public static IReadOnlyList<RealmDataCenterEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RealmDataCenterEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RealmDataCenterEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5],
                (string)row[6],
                (string)row[7],
                (string)row[8],
                (string)row[9],
                (uint)row[10],
                (string)row[11],
                (string)row[12],
                (string)row[13]
            ));
        return list;
    }
}
