// <auto-generated>
// Generated from the client table ResourceConversionGroup.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ResourceConversionGroupEntry(uint ID, uint Flags, uint ResourceConversionId00, uint ResourceConversionId01, uint ResourceConversionId02, uint ResourceConversionId03, uint ResourceConversionId04, uint ResourceConversionId05);

public static class ResourceConversionGroupTable
{
    public static IReadOnlyList<ResourceConversionGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ResourceConversionGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ResourceConversionGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
