// <auto-generated>
// Generated from the client table ResourceConversion.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record ResourceConversionEntry(uint ID, uint ResourceConversionTypeEnum, uint SourceId, uint SourceCount, uint TargetId, uint TargetCount, uint SurchargeId, uint SurchargeCount, uint Flags);

public static class ResourceConversionTable
{
    public static IReadOnlyList<ResourceConversionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<ResourceConversionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new ResourceConversionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
