// <auto-generated>
// Generated from the client table RewardRotationContent.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardRotationContentEntry(uint ID, uint ContentTypeEnum);

public static class RewardRotationContentTable
{
    public static IReadOnlyList<RewardRotationContentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardRotationContentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardRotationContentEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
