// <auto-generated>
// Generated from the client table RewardTrackRewards.tbl (16 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardTrackRewardsEntry(uint ID, uint RewardTrackId, uint RewardPointFlags, uint PrerequisiteId, uint Flags, uint CurrencyTypeId, uint CurrencyAmount, uint RewardTrackRewardTypeEnum00, uint RewardTrackRewardTypeEnum01, uint RewardTrackRewardTypeEnum02, uint RewardChoiceId00, uint RewardChoiceId01, uint RewardChoiceId02, uint RewardChoiceCount00, uint RewardChoiceCount01, uint RewardChoiceCount02);

public static class RewardTrackRewardsTable
{
    public static IReadOnlyList<RewardTrackRewardsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardTrackRewardsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardTrackRewardsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15]
            ));
        return list;
    }
}
