// <auto-generated>
// Generated from the client table RewardRotationItem.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardRotationItemEntry(uint ID, uint RewardItemTypeEnum, uint RewardItemObject, uint Count, string IconPath, uint MinPlayerLevel, uint WorldDifficultyFlags);

public static class RewardRotationItemTable
{
    public static IReadOnlyList<RewardRotationItemEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardRotationItemEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardRotationItemEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (string)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
