// <auto-generated>
// Generated from the client table RewardPropertyPremiumModifier.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardPropertyPremiumModifierEntry(uint ID, uint PremiumSystemEnum, uint Tier, uint RewardPropertyId, uint RewardPropertyData, uint ModifierValueInt, float ModifierValueFloat, uint EntitlementIdModifierCount, uint Flags);

public static class RewardPropertyPremiumModifierTable
{
    public static IReadOnlyList<RewardPropertyPremiumModifierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardPropertyPremiumModifierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardPropertyPremiumModifierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (float)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
