// <auto-generated>
// Generated from the client table RewardTrack.tbl (19 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardTrackEntry(uint ID, uint RewardTrackTypeEnum, uint PrerequisiteId, uint LocalizedTextId, uint LocalizedTextIdSummary, string AssetPathImage, string AssetPathButtonImage, uint RewardPointCost00, uint RewardPointCost01, uint RewardPointCost02, uint RewardPointCost03, uint RewardPointCost04, uint RewardPointCost05, uint RewardPointCost06, uint RewardPointCost07, uint RewardPointCost08, uint RewardPointCost09, uint RewardTrackIdParent, uint Flags);

public static class RewardTrackTable
{
    public static IReadOnlyList<RewardTrackEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardTrackEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardTrackEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5],
                (string)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18]
            ));
        return list;
    }
}
