// <auto-generated>
// Generated from the client table RewardRotationModifier.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardRotationModifierEntry(uint ID, uint RewardPropertyId, uint RewardPropertyData, float Value, uint MinPlayerLevel, uint WorldDifficultyFlags);

public static class RewardRotationModifierTable
{
    public static IReadOnlyList<RewardRotationModifierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardRotationModifierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardRotationModifierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
