// <auto-generated>
// Generated from the client table RewardProperty.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record RewardPropertyEntry(uint ID, uint LocalizedTextId, uint RewardModifierValueTypeEnum);

public static class RewardPropertyTable
{
    public static IReadOnlyList<RewardPropertyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<RewardPropertyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new RewardPropertyEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
