// <auto-generated>
// Generated from the client table SalvageException.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SalvageExceptionEntry(uint ID, uint Item2Id, uint Flags);

public static class SalvageExceptionTable
{
    public static IReadOnlyList<SalvageExceptionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SalvageExceptionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SalvageExceptionEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
