// <auto-generated>
// Generated from the client table Salvage.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SalvageEntry(uint ID, uint Item2TypeId, uint Level);

public static class SalvageTable
{
    public static IReadOnlyList<SalvageEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SalvageEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SalvageEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
