// <auto-generated>
// Generated from the client table SkyCloudSet.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SkyCloudSetEntry(uint ID, float Density, uint SkyTrackCloudSetId00, uint SkyTrackCloudSetId01, uint SkyTrackCloudSetId02, uint SkyTrackCloudSetId03, uint SkyTrackCloudSetId04, uint SkyTrackCloudSetId05);

public static class SkyCloudSetTable
{
    public static IReadOnlyList<SkyCloudSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SkyCloudSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SkyCloudSetEntry(
                (uint)row[0],
                (float)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
