// <auto-generated>
// Generated from the client table SkyTrackCloudSet.tbl (38 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SkyTrackCloudSetEntry(uint ID, uint Count, float MinSize00, float MinSize01, float MinSize02, float MinSize03, float MinSize04, float MinSize05, float MinSize06, float MinSize07, float MinSize08, float MinSize09, float MinSize10, float MinSize11, float MaxSize00, float MaxSize01, float MaxSize02, float MaxSize03, float MaxSize04, float MaxSize05, float MaxSize06, float MaxSize07, float MaxSize08, float MaxSize09, float MaxSize10, float MaxSize11, string Model00, string Model01, string Model02, string Model03, string Model04, string Model05, string Model06, string Model07, string Model08, string Model09, string Model10, string Model11);

public static class SkyTrackCloudSetTable
{
    public static IReadOnlyList<SkyTrackCloudSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SkyTrackCloudSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SkyTrackCloudSetEntry(
                (uint)row[0],
                (uint)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16],
                (float)row[17],
                (float)row[18],
                (float)row[19],
                (float)row[20],
                (float)row[21],
                (float)row[22],
                (float)row[23],
                (float)row[24],
                (float)row[25],
                (string)row[26],
                (string)row[27],
                (string)row[28],
                (string)row[29],
                (string)row[30],
                (string)row[31],
                (string)row[32],
                (string)row[33],
                (string)row[34],
                (string)row[35],
                (string)row[36],
                (string)row[37]
            ));
        return list;
    }
}
