// <auto-generated>
// Generated from the client table SoundImpactEvents.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundImpactEventsEntry(uint ID, uint Origin, uint Target, uint Qualifier, uint Event);

public static class SoundImpactEventsTable
{
    public static IReadOnlyList<SoundImpactEventsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundImpactEventsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundImpactEventsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
