// <auto-generated>
// Generated from the client table SoundEnvironment.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundEnvironmentEntry(uint Id, uint Hash);

public static class SoundEnvironmentTable
{
    public static IReadOnlyList<SoundEnvironmentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundEnvironmentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundEnvironmentEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
