// <auto-generated>
// Generated from the client table SoundStates.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundStatesEntry(uint Id, uint NameHash, uint SoundGroupHash);

public static class SoundStatesTable
{
    public static IReadOnlyList<SoundStatesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundStatesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundStatesEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
