// <auto-generated>
// Generated from the client table SoundDirectionalAmbience.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundDirectionalAmbienceEntry(uint ID, uint SoundEventIdOutsideStart, uint SoundEventIdOutsideStop);

public static class SoundDirectionalAmbienceTable
{
    public static IReadOnlyList<SoundDirectionalAmbienceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundDirectionalAmbienceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundDirectionalAmbienceEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
