// <auto-generated>
// Generated from the client table SoundEvent.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundEventEntry(uint Id, string Name, uint Hash, float Radius, uint SoundBankId00, uint SoundBankId01, uint SoundBankId02, uint SoundBankId03, uint SoundBankId04, uint SoundBankId05, uint SoundBankId06, uint SoundBankId07, uint Flags, uint LimitPriority);

public static class SoundEventTable
{
    public static IReadOnlyList<SoundEventEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundEventEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundEventEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (float)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13]
            ));
        return list;
    }
}
