// <auto-generated>
// Generated from the client table SoundContext.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundContextEntry(uint ID, uint EventId, uint Type);

public static class SoundContextTable
{
    public static IReadOnlyList<SoundContextEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundContextEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundContextEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
