// <auto-generated>
// Generated from the client table SoundUIContext.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundUIContextEntry(uint ID, string LuaVariableName, uint SoundEventId);

public static class SoundUIContextTable
{
    public static IReadOnlyList<SoundUIContextEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundUIContextEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundUIContextEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
