// <auto-generated>
// Generated from the client table SoundSwitch.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundSwitchEntry(uint Id, uint NameHash, uint GroupHash);

public static class SoundSwitchTable
{
    public static IReadOnlyList<SoundSwitchEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundSwitchEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundSwitchEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
