// <auto-generated>
// Generated from the client table SoundCombatLoop.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundCombatLoopEntry(uint ID, uint SoundEventIdStart, uint SoundEventIdStop, uint SoundParameterIdUnitsInCombat);

public static class SoundCombatLoopTable
{
    public static IReadOnlyList<SoundCombatLoopEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundCombatLoopEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundCombatLoopEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
