// <auto-generated>
// Generated from the client table SoundReplaceDescription.tbl (1 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundReplaceDescriptionEntry(uint ID);

public static class SoundReplaceDescriptionTable
{
    public static IReadOnlyList<SoundReplaceDescriptionEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundReplaceDescriptionEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundReplaceDescriptionEntry(
                (uint)row[0]
            ));
        return list;
    }
}
