// <auto-generated>
// Generated from the client table SoundZoneKit.tbl (19 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundZoneKitEntry(uint ID, uint SoundZoneKitIdParent, uint WorldZoneId, uint InheritFlags, uint PropertyFlags, uint SoundMusicSetId, uint SoundEventIdIntro, float IntroReplayWait, uint SoundEventIdMusicMood, uint SoundEventIdAmbientDay, uint SoundEventIdAmbientNight, uint SoundEventIdAmbientUnderwater, uint SoundEventIdAmbientStop, uint SoundEventIdAmbientPreStopOverride, uint SoundEnvironmentId00, uint SoundEnvironmentId01, float EnvironmentDry, float EnvironmentWet00, float EnvironmentWet01);

public static class SoundZoneKitTable
{
    public static IReadOnlyList<SoundZoneKitEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundZoneKitEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundZoneKitEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (float)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (float)row[16],
                (float)row[17],
                (float)row[18]
            ));
        return list;
    }
}
