// <auto-generated>
// Generated from the client table SoundMusicSet.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundMusicSetEntry(uint ID, uint SoundEventIdStart, uint SoundEventIdStop, float RestartDelayMin, float RestartDelayMax, uint Flags);

public static class SoundMusicSetTable
{
    public static IReadOnlyList<SoundMusicSetEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundMusicSetEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundMusicSetEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
