// <auto-generated>
// Generated from the client table SoundBank.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundBankEntry(uint Id, string Name);

public static class SoundBankTable
{
    public static IReadOnlyList<SoundBankEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundBankEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundBankEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
