// <auto-generated>
// Generated from the client table SoundReplace.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SoundReplaceEntry(uint ID, uint SoundReplaceDescriptionId, uint SoundEventIdOld, uint SoundEventIdNew);

public static class SoundReplaceTable
{
    public static IReadOnlyList<SoundReplaceEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SoundReplaceEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SoundReplaceEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
