// <auto-generated>
// Generated from the client table Spell4Reagent.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ReagentEntry(uint ID, uint ReagentType, uint ReagentTypeObjectId, uint ReagentCount, bool ConsumeReagent);

public static class Spell4ReagentTable
{
    public static IReadOnlyList<Spell4ReagentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ReagentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ReagentEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                ((uint)row[4]) != 0
            ));
        return list;
    }
}
