// <auto-generated>
// Generated from the client table Spell4ValidTargets.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ValidTargetsEntry(uint ID, uint TargetBitmask);

public static class Spell4ValidTargetsTable
{
    public static IReadOnlyList<Spell4ValidTargetsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ValidTargetsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ValidTargetsEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
