// <auto-generated>
// Generated from the client table Spell4Prerequisites.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4PrerequisitesEntry(uint ID, uint Flags);

public static class Spell4PrerequisitesTable
{
    public static IReadOnlyList<Spell4PrerequisitesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4PrerequisitesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4PrerequisitesEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
