// <auto-generated>
// Generated from the client table Spell4Base.tbl (42 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4BaseEntry(uint ID, uint LocalizedTextIdName, uint Spell4HitResultId, uint Spell4TargetMechanicId, uint Spell4TargetAngleId, uint Spell4PrerequisiteId, uint Spell4ValidTargetId, uint TargetGroupIdCastGroup, uint Creature2IdPositionalAoe, float ParameterAEAngle, float ParameterAEMaxAngle, float ParameterAEDistance, float ParameterAEMaxDistance, uint TargetGroupIdAoeGroup, uint Spell4BaseIdPrerequisiteSpell, uint WorldZoneIdZoneRequired, uint Spell4SpellTypesIdSpellType, string Icon, uint CastMethod, uint School, uint SpellClass, uint WeaponSlot, uint CastBarType, float MechanicAggressionMagnitude, float MechanicDominationMagnitude, uint ModelSequencePriorityCaster, uint ModelSequencePriorityTarget, uint ClassIdPlayer, uint ClientSideInteractionId, uint TargetingFlags, uint TelegraphFlagsEnum, uint LocalizedTextIdLASTierPoint, float LasTierPointTooltipData00, float LasTierPointTooltipData01, float LasTierPointTooltipData02, float LasTierPointTooltipData03, float LasTierPointTooltipData04, float LasTierPointTooltipData05, float LasTierPointTooltipData06, float LasTierPointTooltipData07, float LasTierPointTooltipData08, float LasTierPointTooltipData09);

public static class Spell4BaseTable
{
    public static IReadOnlyList<Spell4BaseEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4BaseEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4BaseEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (string)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (float)row[23],
                (float)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (float)row[32],
                (float)row[33],
                (float)row[34],
                (float)row[35],
                (float)row[36],
                (float)row[37],
                (float)row[38],
                (float)row[39],
                (float)row[40],
                (float)row[41]
            ));
        return list;
    }
}
