// <auto-generated>
// Generated from the client table SpellCoolDown.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SpellCoolDownEntry(uint ID, uint CooldownTime);

public static class SpellCoolDownTable
{
    public static IReadOnlyList<SpellCoolDownEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SpellCoolDownEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SpellCoolDownEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
