// <auto-generated>
// Generated from the client table Spell4AoeTargetConstraints.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4AoeTargetConstraintsEntry(uint ID, float Angle, uint TargetCount, float MinRange, float MaxRange, uint TargetSelection);

public static class Spell4AoeTargetConstraintsTable
{
    public static IReadOnlyList<Spell4AoeTargetConstraintsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4AoeTargetConstraintsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4AoeTargetConstraintsEntry(
                (uint)row[0],
                (float)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
