// <auto-generated>
// Generated from the client table Spell4EffectModification.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4EffectModificationEntry(uint ID, uint Spell4EffectsId, uint EffectTypeEnum, uint ModificationParameterEnum, uint Priority, uint ModificationTypeEnum, float Data00, float Data01, float Data02, float Data03);

public static class Spell4EffectModificationTable
{
    public static IReadOnlyList<Spell4EffectModificationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4EffectModificationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4EffectModificationEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9]
            ));
        return list;
    }
}
