// <auto-generated>
// Generated from the client table Spell4TargetAngle.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4TargetAngleEntry(uint ID, float TargetAngle);

public static class Spell4TargetAngleTable
{
    public static IReadOnlyList<Spell4TargetAngleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4TargetAngleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4TargetAngleEntry(
                (uint)row[0],
                (float)row[1]
            ));
        return list;
    }
}
