// <auto-generated>
// Generated from the client table Spell4Telegraph.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4TelegraphEntry(uint ID, uint Spell4Id, uint TelegraphDamageId);

public static class Spell4TelegraphTable
{
    public static IReadOnlyList<Spell4TelegraphEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4TelegraphEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4TelegraphEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
