// <auto-generated>
// Generated from the client table Spell4CastResult.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4CastResultEntry(uint ID, string EnumName, uint CombatMessageTypeEnum, uint LocalizedTextIdDisplayText, uint SoundEventId);

public static class Spell4CastResultTable
{
    public static IReadOnlyList<Spell4CastResultEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4CastResultEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4CastResultEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
