// <auto-generated>
// Generated from the client table Spell4CCConditions.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4CCConditionsEntry(uint ID, uint CcStateMask, uint CcStateFlagsRequired);

public static class Spell4CCConditionsTable
{
    public static IReadOnlyList<Spell4CCConditionsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4CCConditionsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4CCConditionsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
