// <auto-generated>
// Generated from the client table SpellLevel.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SpellLevelEntry(uint ID, uint ClassId, uint CharacterLevel, uint PrerequisiteId, uint Spell4Id, float CostMultiplier);

public static class SpellLevelTable
{
    public static IReadOnlyList<SpellLevelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SpellLevelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SpellLevelEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (float)row[5]
            ));
        return list;
    }
}
