// <auto-generated>
// Generated from the client table Spell4Tag.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4TagEntry(uint ID, uint Flags, uint LocalizedTextIdName);

public static class Spell4TagTable
{
    public static IReadOnlyList<Spell4TagEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4TagEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4TagEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
