// <auto-generated>
// Generated from the client table Spell4Visual.tbl (34 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4VisualEntry(uint ID, uint TargetTypeFlags, uint StageType, uint StageFlags, uint VisualEffectId, uint VisualEffectIdSound, uint ModelEventIdDelay, uint SoundEventType00, uint SoundEventType01, uint SoundEventType02, uint SoundEventType03, uint SoundEventType04, uint SoundEventType05, uint SoundImpactDescriptionIdTarget00, uint SoundImpactDescriptionIdTarget01, uint SoundImpactDescriptionIdTarget02, uint SoundImpactDescriptionIdTarget03, uint SoundImpactDescriptionIdTarget04, uint SoundImpactDescriptionIdTarget05, uint SoundImpactDescriptionIdOrigin00, uint SoundImpactDescriptionIdOrigin01, uint SoundImpactDescriptionIdOrigin02, uint SoundImpactDescriptionIdOrigin03, uint SoundImpactDescriptionIdOrigin04, uint SoundImpactDescriptionIdOrigin05, uint ModelAttachmentIdCaster, uint PhaseFlags, float ModelOffsetX, float ModelOffsetY, float ModelOffsetZ, float ModelScale, uint PreDelayTimeMs, uint TelegraphDamageIdAttach, uint PrerequisiteId);

public static class Spell4VisualTable
{
    public static IReadOnlyList<Spell4VisualEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4VisualEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4VisualEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (float)row[27],
                (float)row[28],
                (float)row[29],
                (float)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33]
            ));
        return list;
    }
}
