// <auto-generated>
// Generated from the client table Spell4StackGroup.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4StackGroupEntry(uint ID, uint StackCap, uint StackTypeEnum);

public static class Spell4StackGroupTable
{
    public static IReadOnlyList<Spell4StackGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4StackGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4StackGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
