// <auto-generated>
// Generated from the client table Spell4Effects.tbl (42 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4EffectsEntry(uint ID, uint SpellId, uint TargetFlags, uint EffectType, uint DamageType, uint DelayTime, uint TickTime, uint DurationTime, uint Flags, uint DataBits00, uint DataBits01, uint DataBits02, uint DataBits03, uint DataBits04, uint DataBits05, uint DataBits06, uint DataBits07, uint DataBits08, uint DataBits09, uint InnateCostPerTickType0, uint InnateCostPerTickType1, uint InnateCostPerTick0, uint InnateCostPerTick1, uint EmmComparison, uint EmmValue, float ThreatMultiplier, uint Spell4EffectGroupListId, uint PrerequisiteIdCasterApply, uint PrerequisiteIdTargetApply, uint PrerequisiteIdCasterPersistence, uint PrerequisiteIdTargetPersistence, uint PrerequisiteIdTargetSuspend, uint ParameterType00, uint ParameterType01, uint ParameterType02, uint ParameterType03, float ParameterValue00, float ParameterValue01, float ParameterValue02, float ParameterValue03, uint PhaseFlags, uint OrderIndex);

public static class Spell4EffectsTable
{
    public static IReadOnlyList<Spell4EffectsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4EffectsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4EffectsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (float)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (float)row[36],
                (float)row[37],
                (float)row[38],
                (float)row[39],
                (uint)row[40],
                (uint)row[41]
            ));
        return list;
    }
}
