// <auto-generated>
// Generated from the client table Spell4Thresholds.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ThresholdsEntry(uint ID, uint Spell4IdParent, uint Spell4IdToCast, uint OrderIndex, uint ThresholdDuration, uint VitalEnumCostType00, uint VitalEnumCostType01, uint VitalCostValue00, uint VitalCostValue01, uint LocalizedTextIdTooltip, string IconReplacement, uint VisualEffectId);

public static class Spell4ThresholdsTable
{
    public static IReadOnlyList<Spell4ThresholdsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ThresholdsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ThresholdsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (string)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
