// <auto-generated>
// Generated from the client table SpellPhase.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SpellPhaseEntry(uint ID, uint PhaseDelay, uint PhaseFlags, uint OrderIndex, uint Spell4IdOwner);

public static class SpellPhaseTable
{
    public static IReadOnlyList<SpellPhaseEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SpellPhaseEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SpellPhaseEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
