// <auto-generated>
// Generated from the client table Spell4Modification.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ModificationEntry(uint ID, uint Spell4EffectsId, uint ModificationParameterEnum, uint Priority, uint ModificationTypeEnum, float Data00, float Data01, float Data02, float Data03);

public static class Spell4ModificationTable
{
    public static IReadOnlyList<Spell4ModificationEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ModificationEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ModificationEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8]
            ));
        return list;
    }
}
