// <auto-generated>
// Generated from the client table Spell4Runner.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4RunnerEntry(uint ID, string SpriteName, float RedTint, float GreenTint, float BlueTint, float AlphaTint, float Rate);

public static class Spell4RunnerTable
{
    public static IReadOnlyList<Spell4RunnerEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4RunnerEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4RunnerEntry(
                (uint)row[0],
                (string)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6]
            ));
        return list;
    }
}
