// <auto-generated>
// Generated from the client table Spell4ServiceTokenCost.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ServiceTokenCostEntry(uint ID, uint Spell4Id, uint ServiceTokenCost);

public static class Spell4ServiceTokenCostTable
{
    public static IReadOnlyList<Spell4ServiceTokenCostEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ServiceTokenCostEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ServiceTokenCostEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
