// <auto-generated>
// Generated from the client table Spell4ClientMissile.tbl (53 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ClientMissileEntry(uint ID, uint MissileType, uint CastStage, uint OriginUnitEnum, uint TargetFlags, string ModelPath, string FxPath, string BeamPath, uint BeamSource, uint BeamTarget, uint ItemSlot, uint CostumeSide, uint ModelAttachmentIdCaster, uint ModelAttachmentIdTarget, uint ClientDelay, uint ModelEventIdDelayedBy, uint Flags, uint Duration, uint Frequency, uint SpeedMps, float AccMpss, uint RevolverNestedMissileInitDelay, uint RevolverNestedMissileSubDelay, uint Spell4ClientMissileIdNested, string RevolverMissileImpactAssetPath, uint MissileRevolverTrackId, string BirthAnchorPath, string DeathAnchorPath, string TrajAnchorPath, float BirthDuration, float BirthAnchorAngleMin, float BirthAnchorAngleMax, float DeathAnchorAngleMin, float DeathAnchorAngleMax, uint DeathAnchorSpace, uint ItemSlotIdObj, uint ObjCostumeSide, float TrajPoseFullBlendDistance, float TrajAnchorPlaySpeed, float ParabolaHeightScale, float RotateX, float RotateY, float RotateZ, float Scale, float EndScale, uint PhaseFlags, uint TelegraphDamageIdAttach, uint SoundEventIdBirth, uint SoundEventIdLoopStart, uint SoundEventIdLoopStop, uint SoundEventIdDeath, uint BeamDiffuseColor, uint MissileDiffuseColor);

public static class Spell4ClientMissileTable
{
    public static IReadOnlyList<Spell4ClientMissileEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ClientMissileEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ClientMissileEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (string)row[5],
                (string)row[6],
                (string)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (float)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (string)row[24],
                (uint)row[25],
                (string)row[26],
                (string)row[27],
                (string)row[28],
                (float)row[29],
                (float)row[30],
                (float)row[31],
                (float)row[32],
                (float)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (float)row[37],
                (float)row[38],
                (float)row[39],
                (float)row[40],
                (float)row[41],
                (float)row[42],
                (float)row[43],
                (float)row[44],
                (uint)row[45],
                (uint)row[46],
                (uint)row[47],
                (uint)row[48],
                (uint)row[49],
                (uint)row[50],
                (uint)row[51],
                (uint)row[52]
            ));
        return list;
    }
}
