// <auto-generated>
// Generated from the client table Spell4TargetMechanics.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4TargetMechanicsEntry(uint ID, uint TargetType, uint Flags);

public static class Spell4TargetMechanicsTable
{
    public static IReadOnlyList<Spell4TargetMechanicsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4TargetMechanicsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4TargetMechanicsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
