// <auto-generated>
// Generated from the client table Spell4Conditions.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4ConditionsEntry(uint ID, uint ConditionMask, uint ConditionValue);

public static class Spell4ConditionsTable
{
    public static IReadOnlyList<Spell4ConditionsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4ConditionsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4ConditionsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
