// <auto-generated>
// Generated from the client table SpellEffectType.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record SpellEffectTypeEntry(uint ID, uint Flags, uint DataType00, uint DataType01, uint DataType02, uint DataType03, uint DataType04, uint DataType05, uint DataType06, uint DataType07, uint DataType08, uint DataType09);

public static class SpellEffectTypeTable
{
    public static IReadOnlyList<SpellEffectTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<SpellEffectTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new SpellEffectTypeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
