// <auto-generated>
// Generated from the client table Spell4TierRequirements.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4TierRequirementsEntry(uint ID, uint TierIndex, uint LevelRequirement);

public static class Spell4TierRequirementsTable
{
    public static IReadOnlyList<Spell4TierRequirementsEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4TierRequirementsEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4TierRequirementsEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
