// <auto-generated>
// Generated from the client table Spell4VisualGroup.tbl (38 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4VisualGroupEntry(uint ID, uint Spell4VisualIdVisual00, uint Spell4VisualIdVisual01, uint Spell4VisualIdVisual02, uint Spell4VisualIdVisual03, uint Spell4VisualIdVisual04, uint Spell4VisualIdVisual05, uint Spell4VisualIdVisual06, uint Spell4VisualIdVisual07, uint Spell4VisualIdVisual08, uint Spell4VisualIdVisual09, uint Spell4VisualIdVisual10, uint Spell4VisualIdVisual11, uint Spell4VisualIdVisual12, uint Spell4VisualIdVisual13, uint Spell4VisualIdVisual14, uint Spell4VisualIdVisual15, uint Spell4VisualIdVisual16, uint Spell4VisualIdVisual17, uint Spell4VisualIdVisual18, uint Spell4VisualIdVisual19, uint Spell4VisualIdVisual20, uint Spell4VisualIdVisual21, uint Spell4VisualIdVisual22, uint Spell4VisualIdVisual23, uint Spell4VisualIdVisual24, uint Spell4VisualIdVisual25, uint Spell4VisualIdVisual26, uint Spell4VisualIdVisual27, uint Spell4VisualIdVisual28, uint Spell4VisualIdVisual29, uint Spell4VisualIdVisual30, uint Spell4VisualIdVisual31, uint Spell4VisualIdVisual32, uint Spell4VisualIdVisual33, uint Spell4VisualIdVisual34, uint Spell4VisualIdVisual35, uint VisualEffectIdPrimaryCaster);

public static class Spell4VisualGroupTable
{
    public static IReadOnlyList<Spell4VisualGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4VisualGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4VisualGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37]
            ));
        return list;
    }
}
