// <auto-generated>
// Generated from the client table Spell4EffectGroupList.tbl (33 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4EffectGroupListEntry(uint ID, uint Spell4EffectGroupId00, uint Spell4EffectGroupId01, uint Spell4EffectGroupId02, uint Spell4EffectGroupId03, uint Spell4EffectGroupId04, uint Spell4EffectGroupId05, uint Spell4EffectGroupId06, uint Spell4EffectGroupId07, uint Spell4EffectGroupId08, uint Spell4EffectGroupId09, uint Spell4EffectGroupId10, uint Spell4EffectGroupId11, uint Spell4EffectGroupId12, uint Spell4EffectGroupId13, uint Spell4EffectGroupId14, uint Spell4EffectGroupId15, uint Spell4EffectGroupId16, uint Spell4EffectGroupId17, uint Spell4EffectGroupId18, uint Spell4EffectGroupId19, uint Spell4EffectGroupId20, uint Spell4EffectGroupId21, uint Spell4EffectGroupId22, uint Spell4EffectGroupId23, uint Spell4EffectGroupId24, uint Spell4EffectGroupId25, uint Spell4EffectGroupId26, uint Spell4EffectGroupId27, uint Spell4EffectGroupId28, uint Spell4EffectGroupId29, uint Spell4EffectGroupId30, uint Spell4EffectGroupId31);

public static class Spell4EffectGroupListTable
{
    public static IReadOnlyList<Spell4EffectGroupListEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4EffectGroupListEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4EffectGroupListEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32]
            ));
        return list;
    }
}
