// <auto-generated>
// Generated from the client table Spell4SpellTypes.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4SpellTypesEntry(uint ID, string TypeName, string EnumName);

public static class Spell4SpellTypesTable
{
    public static IReadOnlyList<Spell4SpellTypesEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4SpellTypesEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4SpellTypesEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2]
            ));
        return list;
    }
}
