// <auto-generated>
// Generated from the client table Spell4GroupList.tbl (33 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spell4GroupListEntry(uint ID, uint SpellGroupId00, uint SpellGroupId01, uint SpellGroupId02, uint SpellGroupId03, uint SpellGroupId04, uint SpellGroupId05, uint SpellGroupId06, uint SpellGroupId07, uint SpellGroupId08, uint SpellGroupId09, uint SpellGroupId10, uint SpellGroupId11, uint SpellGroupId12, uint SpellGroupId13, uint SpellGroupId14, uint SpellGroupId15, uint SpellGroupId16, uint SpellGroupId17, uint SpellGroupId18, uint SpellGroupId19, uint SpellGroupId20, uint SpellGroupId21, uint SpellGroupId22, uint SpellGroupId23, uint SpellGroupId24, uint SpellGroupId25, uint SpellGroupId26, uint SpellGroupId27, uint SpellGroupId28, uint SpellGroupId29, uint SpellGroupId30, uint SpellGroupId31);

public static class Spell4GroupListTable
{
    public static IReadOnlyList<Spell4GroupListEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spell4GroupListEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spell4GroupListEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32]
            ));
        return list;
    }
}
