// <auto-generated>
// Generated from the client table Spline2.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spline2Entry(uint ID, uint WorldId, uint SplineType);

public static class Spline2Table
{
    public static IReadOnlyList<Spline2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spline2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spline2Entry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
