// <auto-generated>
// Generated from the client table Spline2Node.tbl (14 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record Spline2NodeEntry(uint ID, uint SplineId, uint Ordinal, float Position0, float Position1, float Position2, float Facing0, float Facing1, float Facing2, float Facing3, uint EventId, float FrameTime, float Delay, float Fovy);

public static class Spline2NodeTable
{
    public static IReadOnlyList<Spline2NodeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<Spline2NodeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new Spline2NodeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (uint)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13]
            ));
        return list;
    }
}
