// <auto-generated>
// Generated from the client table StoreKeyword.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record StoreKeywordEntry(uint ID, uint StoreDisplayInfoId, string Keyword);

public static class StoreKeywordTable
{
    public static IReadOnlyList<StoreKeywordEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<StoreKeywordEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new StoreKeywordEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2]
            ));
        return list;
    }
}
