// <auto-generated>
// Generated from the client table StoreDisplayInfo.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record StoreDisplayInfoEntry(uint ID, uint DisplayType, uint DisplayValue, uint ModelCameraId, uint LocalizedTextIdName);

public static class StoreDisplayInfoTable
{
    public static IReadOnlyList<StoreDisplayInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<StoreDisplayInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new StoreDisplayInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
