// <auto-generated>
// Generated from the client table StoryPanel.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record StoryPanelEntry(uint ID, uint LocalizedTextIdBody, uint SoundEventId, uint WindowTypeId, uint DurationMS, uint PrerequisiteId, uint StoryPanelStyleEnum);

public static class StoryPanelTable
{
    public static IReadOnlyList<StoryPanelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<StoryPanelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new StoryPanelEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
