// <auto-generated>
// Generated from the client table StoreLink.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record StoreLinkEntry(uint ID, string EnumName, uint CategoryData, uint CategoryDataPTR, uint AccountItemId);

public static class StoreLinkTable
{
    public static IReadOnlyList<StoreLinkEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<StoreLinkEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new StoreLinkEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
