// <auto-generated>
// Generated from the client table TargetGroup.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TargetGroupEntry(uint ID, uint LocalizedTextIdDisplayString, uint Type, uint Data0, uint Data1, uint Data2, uint Data3, uint Data4, uint Data5, uint Data6);

public static class TargetGroupTable
{
    public static IReadOnlyList<TargetGroupEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TargetGroupEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TargetGroupEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
