// <auto-generated>
// Generated from the client table TargetMarker.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TargetMarkerEntry(uint ID, uint VisualEffectId, string IconPath);

public static class TargetMarkerTable
{
    public static IReadOnlyList<TargetMarkerEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TargetMarkerEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TargetMarkerEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2]
            ));
        return list;
    }
}
