// <auto-generated>
// Generated from the client table TaxiRoute.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TaxiRouteEntry(uint ID, uint TaxiNodeIdSource, uint TaxiNodeIdDestination, uint Price);

public static class TaxiRouteTable
{
    public static IReadOnlyList<TaxiRouteEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TaxiRouteEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TaxiRouteEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
