// <auto-generated>
// Generated from the client table TelegraphDamage.tbl (25 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TelegraphDamageEntry(uint ID, uint TelegraphSubtypeEnum, uint DamageShapeEnum, float Param00, float Param01, float Param02, float Param03, float Param04, float Param05, uint TelegraphTimeStartMs, uint TelegraphTimeEndMs, uint TelegraphTimeRampInMs, uint TelegraphTimeRampOutMs, float XPositionOffset, float YPositionOffset, float ZPositionOffset, float RotationDegrees, uint TelegraphDamageFlags, uint TargetTypeFlags, uint PhaseFlags, uint PrerequisiteIdCaster, uint SpellThresholdRestrictionFlags, uint DisplayFlags, uint OpacityModifier, uint DisplayGroup);

public static class TelegraphDamageTable
{
    public static IReadOnlyList<TelegraphDamageEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TelegraphDamageEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TelegraphDamageEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24]
            ));
        return list;
    }
}
