// <auto-generated>
// Generated from the client table TicketSubCategory.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TicketSubCategoryEntry(uint ID, uint TicketCategoryId, uint LocalizedTextId);

public static class TicketSubCategoryTable
{
    public static IReadOnlyList<TicketSubCategoryEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TicketSubCategoryEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TicketSubCategoryEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
