// <auto-generated>
// Generated from the client table TrackingSlot.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TrackingSlotEntry(uint ID, uint LocalizedTextIdLabel, string IconPath, uint PublicEventObjectiveId);

public static class TrackingSlotTable
{
    public static IReadOnlyList<TrackingSlotEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TrackingSlotEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TrackingSlotEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
