// <auto-generated>
// Generated from the client table Tradeskill.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillEntry(uint ID, uint LocalizedTextIdName, uint LocalizedTextIdDescription, uint Flags, uint TutorialId, uint AchievementCategoryId, uint MaxAdditives, uint LocalizedTextIdAxisName00, uint LocalizedTextIdAxisName01, uint LocalizedTextIdAxisName02, uint LocalizedTextIdAxisName03);

public static class TradeskillTable
{
    public static IReadOnlyList<TradeskillEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
