// <auto-generated>
// Generated from the client table TradeskillTalentTier.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillTalentTierEntry(uint ID, uint TradeSkillId, uint PointsToUnlock, uint RespecCost, uint TradeSkillBonusId00, uint TradeSkillBonusId01, uint TradeSkillBonusId02, uint TradeSkillBonusId03, uint TradeSkillBonusId04);

public static class TradeskillTalentTierTable
{
    public static IReadOnlyList<TradeskillTalentTierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillTalentTierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillTalentTierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
