// <auto-generated>
// Generated from the client table TradeskillTier.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillTierEntry(uint ID, uint TradeSkillId, uint Tier, uint RequiredXp, uint LearnXp, uint CraftXp, uint FirstCraftXp, uint QuestXp, uint FailXp, uint ItemLevelMin, uint MaxAdditives, ulong RelearnCost, uint AchievementCategoryId);

public static class TradeskillTierTable
{
    public static IReadOnlyList<TradeskillTierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillTierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillTierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (ulong)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
