// <auto-generated>
// Generated from the client table TradeskillMaterial.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillMaterialEntry(uint ID, uint Item2IdStatRevolution, uint Item2Id, uint DisplayIndex, uint TradeskillMaterialCategoryId);

public static class TradeskillMaterialTable
{
    public static IReadOnlyList<TradeskillMaterialEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillMaterialEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillMaterialEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
