// <auto-generated>
// Generated from the client table TradeskillAchievementReward.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillAchievementRewardEntry(uint ID, uint AchievementId, uint Faction2Id, uint FactionIdAmount, uint TalentPoints, uint TradeSkillSchematicId00, uint TradeSkillSchematicId01, uint TradeSkillSchematicId02, uint TradeSkillSchematicId03, uint TradeSkillSchematicId04, uint TradeSkillSchematicId05, uint TradeSkillSchematicId06, uint TradeSkillSchematicId07);

public static class TradeskillAchievementRewardTable
{
    public static IReadOnlyList<TradeskillAchievementRewardEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillAchievementRewardEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillAchievementRewardEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
