// <auto-generated>
// Generated from the client table TradeskillHarvestingInfo.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillHarvestingInfoEntry(uint ID, uint TradeSkillTierId, uint PrerequisiteId, uint MiniMapMarkerId);

public static class TradeskillHarvestingInfoTable
{
    public static IReadOnlyList<TradeskillHarvestingInfoEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillHarvestingInfoEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillHarvestingInfoEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
