// <auto-generated>
// Generated from the client table TradeskillAchievementLayout.tbl (9 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillAchievementLayoutEntry(uint ID, uint AchievementId, uint AchievementIdParent00, uint AchievementIdParent01, uint AchievementIdParent02, uint AchievementIdParent03, uint AchievementIdParent04, uint GridX, uint GridY);

public static class TradeskillAchievementLayoutTable
{
    public static IReadOnlyList<TradeskillAchievementLayoutEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillAchievementLayoutEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillAchievementLayoutEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8]
            ));
        return list;
    }
}
