// <auto-generated>
// Generated from the client table TradeskillAdditive.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillAdditiveEntry(uint ID, uint TradeSkillId, uint Tier, float VectorX, float VectorY, float Radius);

public static class TradeskillAdditiveTable
{
    public static IReadOnlyList<TradeskillAdditiveEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillAdditiveEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillAdditiveEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5]
            ));
        return list;
    }
}
