// <auto-generated>
// Generated from the client table TradeskillBonus.tbl (24 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillBonusEntry(uint ID, uint TradeSkillTierId, uint AchievementId, string IconPath, uint LocalizedTextIdName, uint LocalizedTextIdTooltip, uint TradeskillBonusEnum00, uint TradeskillBonusEnum01, uint TradeskillBonusEnum02, uint ObjectIdPrimary00, uint ObjectIdPrimary01, uint ObjectIdPrimary02, uint ObjectIdSecondary00, uint ObjectIdSecondary01, uint ObjectIdSecondary02, uint ObjectIdTertiary00, uint ObjectIdTertiary01, uint ObjectIdTertiary02, float Value00, float Value01, float Value02, uint ValueInt00, uint ValueInt01, uint ValueInt02);

public static class TradeskillBonusTable
{
    public static IReadOnlyList<TradeskillBonusEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillBonusEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillBonusEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (string)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (float)row[18],
                (float)row[19],
                (float)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23]
            ));
        return list;
    }
}
