// <auto-generated>
// Generated from the client table TradeskillCatalystOrdering.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillCatalystOrderingEntry(uint ID, uint UnlockLevel00, uint UnlockLevel01, uint UnlockLevel02, uint UnlockLevel03, uint UnlockLevel04);

public static class TradeskillCatalystOrderingTable
{
    public static IReadOnlyList<TradeskillCatalystOrderingEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillCatalystOrderingEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillCatalystOrderingEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
