// <auto-generated>
// Generated from the client table TradeskillSchematic2.tbl (32 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TradeskillSchematic2Entry(uint ID, uint LocalizedTextIdName, uint TradeSkillId, uint Item2IdOutput, uint Item2IdOutputFail, uint OutputCount, uint LootId, uint Tier, uint Flags, uint Item2IdMaterial00, uint Item2IdMaterial01, uint Item2IdMaterial02, uint Item2IdMaterial03, uint Item2IdMaterial04, uint MaterialCost00, uint MaterialCost01, uint MaterialCost02, uint MaterialCost03, uint MaterialCost04, uint TradeskillSchematic2IdParent, float VectorX, float VectorY, float Radius, float CritRadius, uint Item2IdOutputCrit, uint OutputCountCritBonus, uint Priority, uint MaxAdditives, uint DiscoverableQuadrant, float DiscoverableRadius, float DiscoverableAngle, uint TradeskillCatalystOrderingId);

public static class TradeskillSchematic2Table
{
    public static IReadOnlyList<TradeskillSchematic2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TradeskillSchematic2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TradeskillSchematic2Entry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (float)row[20],
                (float)row[21],
                (float)row[22],
                (float)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (float)row[29],
                (float)row[30],
                (uint)row[31]
            ));
        return list;
    }
}
