// <auto-generated>
// Generated from the client table TutorialLayout.tbl (3 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TutorialLayoutEntry(uint ID, string Form, uint Flags);

public static class TutorialLayoutTable
{
    public static IReadOnlyList<TutorialLayoutEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TutorialLayoutEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TutorialLayoutEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2]
            ));
        return list;
    }
}
