// <auto-generated>
// Generated from the client table Tutorial.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TutorialEntry(uint ID, uint Flags, uint TutorialCategoryEnum, uint LocalizedTextIdContextualPopup, uint TutorialAnchorId, uint RequiredLevel, uint PrerequisiteId);

public static class TutorialTable
{
    public static IReadOnlyList<TutorialEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TutorialEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TutorialEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
