// <auto-generated>
// Generated from the client table TutorialPage.tbl (12 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TutorialPageEntry(uint ID, uint TutorialId, uint Page, uint TutorialLayoutId, uint LocalizedTextIdTitle, uint LocalizedTextIdBody00, uint LocalizedTextIdBody01, uint LocalizedTextIdBody02, string Sprite00, string Sprite01, string Sprite02, uint SoundEventId);

public static class TutorialPageTable
{
    public static IReadOnlyList<TutorialPageEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TutorialPageEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TutorialPageEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (string)row[8],
                (string)row[9],
                (string)row[10],
                (uint)row[11]
            ));
        return list;
    }
}
