// <auto-generated>
// Generated from the client table TutorialAnchor.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record TutorialAnchorEntry(uint ID, uint TutorialAnchorOrientationEnum, uint HOffset, uint VOffset, uint Flags);

public static class TutorialAnchorTable
{
    public static IReadOnlyList<TutorialAnchorEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<TutorialAnchorEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new TutorialAnchorEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
