// <auto-generated>
// Generated from the client table UnitVehicle.tbl (30 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record UnitVehicleEntry(uint ID, uint VehicleTypeEnum, uint NumberPilots, uint PilotPosture00, uint PilotPosture01, uint NumberPassengers, uint PassengerPosture00, uint PassengerPosture01, uint PassengerPosture02, uint PassengerPosture03, uint PassengerPosture04, uint PassengerPosture05, uint NumberGunners, uint GunnerPosture00, uint GunnerPosture01, uint GunnerPosture02, uint GunnerPosture03, uint GunnerPosture04, uint GunnerPosture05, uint VendorItemPrice, uint LocalizedTextIdName, uint LocalizedTextIdTooltip, string ButtonIcon, uint Flags, uint SoundEventIdTakeoff, uint SoundEventIdLanding, uint WaterSurfaceEffectIdMoving, uint WaterSurfaceEffectIdStanding, uint WaterSurfaceEffectIdJumpIn, uint WaterSurfaceEffectIdJumpOut);

public static class UnitVehicleTable
{
    public static IReadOnlyList<UnitVehicleEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<UnitVehicleEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new UnitVehicleEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (string)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29]
            ));
        return list;
    }
}
