// <auto-generated>
// Generated from the client table UnitProperty2.tbl (11 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record UnitProperty2Entry(uint ID, string Description, string EnumName, float DefaultValue, uint LocalizedTextId, float ValuePerPoint, uint Flags, uint TooltipDisplayOrder, uint ProfiencyFlagEnum, uint ItemCraftingGroupFlagBitMask, uint EquippedSlotFlags);

public static class UnitProperty2Table
{
    public static IReadOnlyList<UnitProperty2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<UnitProperty2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new UnitProperty2Entry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (float)row[3],
                (uint)row[4],
                (float)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10]
            ));
        return list;
    }
}
