// <auto-generated>
// Generated from the client table VeteranTier.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record VeteranTierEntry(uint ID, uint PrimeLevel, uint VeteranTierScalingType, uint UnitPropertyOverrideMenace);

public static class VeteranTierTable
{
    public static IReadOnlyList<VeteranTierEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<VeteranTierEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new VeteranTierEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
