// <auto-generated>
// Generated from the client table VirtualItem.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record VirtualItemEntry(uint ID, string ButtonIcon, uint Item2TypeId, uint LocalizedTextIdName, uint LocalizedTextIdFlavor, uint ItemQualityId);

public static class VirtualItemTable
{
    public static IReadOnlyList<VirtualItemEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<VirtualItemEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new VirtualItemEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
