// <auto-generated>
// Generated from the client table VisualEffect.tbl (38 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record VisualEffectEntry(uint ID, uint VisualType, uint StartDelay, uint Duration, uint ModelItemSlot, uint ModelItemCostumeSide, string ModelAssetPath, uint ModelAttachmentId, uint ModelSequencePriority, uint ModelSequenceIdTarget00, uint ModelSequenceIdTarget01, uint ModelSequenceIdTarget02, float ModelScale, float ModelRotationX, float ModelRotationY, float ModelRotationZ, float Data00, float Data01, float Data02, float Data03, float Data04, uint Flags, uint SoundEventId00, uint SoundEventId01, uint SoundEventId02, uint SoundEventId03, uint SoundEventId04, uint SoundEventId05, uint SoundEventOffset00, uint SoundEventOffset01, uint SoundEventOffset02, uint SoundEventOffset03, uint SoundEventOffset04, uint SoundEventOffset05, uint SoundEventIdStop, uint SoundZoneKitId, uint PrerequisiteId, uint ParticleDiffuseColor);

public static class VisualEffectTable
{
    public static IReadOnlyList<VisualEffectEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<VisualEffectEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new VisualEffectEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (string)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16],
                (float)row[17],
                (float)row[18],
                (float)row[19],
                (float)row[20],
                (uint)row[21],
                (uint)row[22],
                (uint)row[23],
                (uint)row[24],
                (uint)row[25],
                (uint)row[26],
                (uint)row[27],
                (uint)row[28],
                (uint)row[29],
                (uint)row[30],
                (uint)row[31],
                (uint)row[32],
                (uint)row[33],
                (uint)row[34],
                (uint)row[35],
                (uint)row[36],
                (uint)row[37]
            ));
        return list;
    }
}
