// <auto-generated>
// Generated from the client table Vital.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record VitalEntry(uint ID, uint LocalizedTextIdDisplayText);

public static class VitalTable
{
    public static IReadOnlyList<VitalEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<VitalEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new VitalEntry(
                (uint)row[0],
                (uint)row[1]
            ));
        return list;
    }
}
