// <auto-generated>
// Generated from the client table WaterSurfaceEffect.tbl (8 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WaterSurfaceEffectEntry(uint ID, uint EmissionDelay, uint WorldWaterWakeIdStillWater0, uint WorldWaterWakeIdStillWater1, uint VisualEffectIdParticle0, uint VisualEffectIdParticle1, uint ParticleFlags0, uint ParticleFlags1);

public static class WaterSurfaceEffectTable
{
    public static IReadOnlyList<WaterSurfaceEffectEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WaterSurfaceEffectEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WaterSurfaceEffectEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7]
            ));
        return list;
    }
}
