// <auto-generated>
// Generated from the client table Wind.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WindEntry(uint ID, uint Type, uint Duration, float RadiusEnd, float Direction, float DirectionDelta, float BlendIn, float BlendOut, float Speed, float Sine2DMagnitudeMin, float Sine2DMagnitudeMax, float Sine2DFrequency, float Sine2DOffsetAngle, uint LocalRadial, float LocalMagnitude);

public static class WindTable
{
    public static IReadOnlyList<WindEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WindEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WindEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (uint)row[13],
                (float)row[14]
            ));
        return list;
    }
}
