// <auto-generated>
// Generated from the client table WordFilterAlt.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WordFilterAltEntry(uint ID, string Filter);

public static class WordFilterAltTable
{
    public static IReadOnlyList<WordFilterAltEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WordFilterAltEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WordFilterAltEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
