// <auto-generated>
// Generated from the client table WordFilter.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WordFilterEntry(uint ID, string Filter, uint UserTextFilterClassEnum, uint DeploymentRegionEnum, uint LanguageId, uint WordFilterTypeEnum);

public static class WordFilterTable
{
    public static IReadOnlyList<WordFilterEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WordFilterEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WordFilterEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
