// <auto-generated>
// Generated from the client table WorldLocation2.tbl (13 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldLocation2Entry(uint ID, float Radius, float MaxVerticalDistance, float Position0, float Position1, float Position2, float Facing0, float Facing1, float Facing2, float Facing3, uint WorldId, uint WorldZoneId, uint Phases);

public static class WorldLocation2Table
{
    public static IReadOnlyList<WorldLocation2Entry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldLocation2Entry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldLocation2Entry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12]
            ));
        return list;
    }
}
