// <auto-generated>
// Generated from the client table WorldLayer.tbl (20 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldLayerEntry(uint ID, string Description, float HeightScale, float HeightOffset, float ParallaxScale, float ParallaxOffset, float MetersPerTextureTile, string ColorMapPath, string NormalMapPath, uint AverageColor, uint Projection, uint MaterialType, uint WorldClutterId00, uint WorldClutterId01, uint WorldClutterId02, uint WorldClutterId03, float SpecularPower, uint EmissiveGlow, float ScrollSpeed00, float ScrollSpeed01);

public static class WorldLayerTable
{
    public static IReadOnlyList<WorldLayerEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldLayerEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldLayerEntry(
                (uint)row[0],
                (string)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (string)row[7],
                (string)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (float)row[16],
                (uint)row[17],
                (float)row[18],
                (float)row[19]
            ));
        return list;
    }
}
