// <auto-generated>
// Generated from the client table WorldWaterEnvironment.tbl (2 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldWaterEnvironmentEntry(uint ID, string LandMapPath);

public static class WorldWaterEnvironmentTable
{
    public static IReadOnlyList<WorldWaterEnvironmentEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldWaterEnvironmentEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldWaterEnvironmentEntry(
                (uint)row[0],
                (string)row[1]
            ));
        return list;
    }
}
