// <auto-generated>
// Generated from the client table WorldClutter.tbl (46 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldClutterEntry(uint ID, string Description, float Density, uint ClutterFlags, string AssetPath0, string AssetPath01, string AssetPath02, string AssetPath03, string AssetPath04, string AssetPath05, float AssetWeight0, float AssetWeight01, float AssetWeight02, float AssetWeight03, float AssetWeight04, float AssetWeight05, uint Flag0, uint Flag01, uint Flag02, uint Flag03, uint Flag04, uint Flag05, float MinScale0, float MinScale01, float MinScale02, float MinScale03, float MinScale04, float MinScale05, float RotationMin0, float RotationMin01, float RotationMin02, float RotationMin03, float RotationMin04, float RotationMin05, float RotationMax0, float RotationMax01, float RotationMax02, float RotationMax03, float RotationMax04, float RotationMax05, uint EmissiveGlow00, uint EmissiveGlow01, uint EmissiveGlow02, uint EmissiveGlow03, uint EmissiveGlow04, uint EmissiveGlow05);

public static class WorldClutterTable
{
    public static IReadOnlyList<WorldClutterEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldClutterEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldClutterEntry(
                (uint)row[0],
                (string)row[1],
                (float)row[2],
                (uint)row[3],
                (string)row[4],
                (string)row[5],
                (string)row[6],
                (string)row[7],
                (string)row[8],
                (string)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18],
                (uint)row[19],
                (uint)row[20],
                (uint)row[21],
                (float)row[22],
                (float)row[23],
                (float)row[24],
                (float)row[25],
                (float)row[26],
                (float)row[27],
                (float)row[28],
                (float)row[29],
                (float)row[30],
                (float)row[31],
                (float)row[32],
                (float)row[33],
                (float)row[34],
                (float)row[35],
                (float)row[36],
                (float)row[37],
                (float)row[38],
                (float)row[39],
                (uint)row[40],
                (uint)row[41],
                (uint)row[42],
                (uint)row[43],
                (uint)row[44],
                (uint)row[45]
            ));
        return list;
    }
}
