// <auto-generated>
// Generated from the client table WorldZone.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldZoneEntry(uint ID, uint LocalizedTextIdName, uint ParentZoneId, bool AllowAccess, uint Color, uint SoundZoneKitId, uint WorldLocation2IdExit, uint Flags, uint ZonePvpRulesEnum, uint RewardRotationContentId);

public static class WorldZoneTable
{
    public static IReadOnlyList<WorldZoneEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldZoneEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldZoneEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                ((uint)row[3]) != 0,
                (uint)row[4],
                (uint)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
