// <auto-generated>
// Generated from the client table WorldWaterLayer.tbl (15 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldWaterLayerEntry(uint ID, string Description, string RippleColorTex, string RippleNormalTex, float Scale, float Rotation, float Speed, float OscFrequency, float OscMagnitude, float OscRotation, float OscPhase, float OscMinLayerWeight, float OscMaxLayerWeight, float OscLayerWeightPhase, float MaterialBlend);

public static class WorldWaterLayerTable
{
    public static IReadOnlyList<WorldWaterLayerEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldWaterLayerEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldWaterLayerEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (string)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14]
            ));
        return list;
    }
}
