// <auto-generated>
// Generated from the client table WorldSky.tbl (4 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldSkyEntry(uint ID, string AssetPath, string AssetPathInFlux, uint Color);

public static class WorldSkyTable
{
    public static IReadOnlyList<WorldSkyEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldSkyEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldSkyEntry(
                (uint)row[0],
                (string)row[1],
                (string)row[2],
                (uint)row[3]
            ));
        return list;
    }
}
