// <auto-generated>
// Generated from the client table World.tbl (19 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldEntry(uint ID, string AssetPath, uint Flags, uint Type, string ScreenPath, string ScreenModelPath, uint ChunkBounds00, uint ChunkBounds01, uint ChunkBounds02, uint ChunkBounds03, uint PlugAverageHeight, uint LocalizedTextIdName, uint MinItemLevel, uint MaxItemLevel, uint PrimeLevelOffset, uint PrimeLevelMax, uint VeteranTierScalingType, uint HeroismMenaceLevel, uint RewardRotationContentId);

public static class WorldTable
{
    public static IReadOnlyList<WorldEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldEntry(
                (uint)row[0],
                (string)row[1],
                (uint)row[2],
                (uint)row[3],
                (string)row[4],
                (string)row[5],
                (uint)row[6],
                (uint)row[7],
                (uint)row[8],
                (uint)row[9],
                (uint)row[10],
                (uint)row[11],
                (uint)row[12],
                (uint)row[13],
                (uint)row[14],
                (uint)row[15],
                (uint)row[16],
                (uint)row[17],
                (uint)row[18]
            ));
        return list;
    }
}
