// <auto-generated>
// Generated from the client table WorldWaterWake.tbl (18 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldWaterWakeEntry(uint ID, uint Flags, string ColorTexture, string NormalTexture, string DistortionTexture, uint DurationMin, uint DurationMax, float ScaleStart, float ScaleEnd, float AlphaStart, float AlphaEnd, float DistortionWeight, float DistortionScaleStart, float DistortionScaleEnd, float DistortionSpeedU, float DistortionSpeedV, float PositionOffsetX, float PositionOffsetY);

public static class WorldWaterWakeTable
{
    public static IReadOnlyList<WorldWaterWakeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldWaterWakeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldWaterWakeEntry(
                (uint)row[0],
                (uint)row[1],
                (string)row[2],
                (string)row[3],
                (string)row[4],
                (uint)row[5],
                (uint)row[6],
                (float)row[7],
                (float)row[8],
                (float)row[9],
                (float)row[10],
                (float)row[11],
                (float)row[12],
                (float)row[13],
                (float)row[14],
                (float)row[15],
                (float)row[16],
                (float)row[17]
            ));
        return list;
    }
}
