// <auto-generated>
// Generated from the client table WorldWaterFog.tbl (10 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldWaterFogEntry(uint ID, float FogStart, float FogEnd, float FogStartUW, float FogEndUW, float ModStart, float ModEnd, float ModStartUW, float ModEndUW, uint SkyColorIndex);

public static class WorldWaterFogTable
{
    public static IReadOnlyList<WorldWaterFogEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldWaterFogEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldWaterFogEntry(
                (uint)row[0],
                (float)row[1],
                (float)row[2],
                (float)row[3],
                (float)row[4],
                (float)row[5],
                (float)row[6],
                (float)row[7],
                (float)row[8],
                (uint)row[9]
            ));
        return list;
    }
}
