// <auto-generated>
// Generated from the client table WorldSocket.tbl (7 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldSocketEntry(uint ID, uint WorldId, uint Bounds0, uint Bounds1, uint Bounds2, uint Bounds3, uint AverageHeight);

public static class WorldSocketTable
{
    public static IReadOnlyList<WorldSocketEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldSocketEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldSocketEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5],
                (uint)row[6]
            ));
        return list;
    }
}
