// <auto-generated>
// Generated from the client table WorldWaterType.tbl (5 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record WorldWaterTypeEntry(uint ID, uint WorldWaterFogId, uint SurfaceType, string ParticleFile, uint SoundDirectionalAmbienceId);

public static class WorldWaterTypeTable
{
    public static IReadOnlyList<WorldWaterTypeEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<WorldWaterTypeEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new WorldWaterTypeEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (string)row[3],
                (uint)row[4]
            ));
        return list;
    }
}
