// <auto-generated>
// Generated from the client table XpPerLevel.tbl (6 fields).
// The schema is a fact about Carbine's file; do not edit by hand - regenerate.
// </auto-generated>
using System.Collections.Generic;
using NexusUnleashed.GameData;

namespace NexusUnleashed.GameData.Generated;

public sealed record XpPerLevelEntry(uint ID, uint MinXpForLevel, uint BaseQuestXpPerLevel, uint AbilityPointsPerLevel, uint AttributePointsPerLevel, uint BaseRepRewardPerLevel);

public static class XpPerLevelTable
{
    public static IReadOnlyList<XpPerLevelEntry> Load(string tblPath)
    {
        var t = GameTableReader.Read(tblPath);
        var list = new List<XpPerLevelEntry>(t.Rows.Count);
        foreach (var row in t.Rows)
            list.Add(new XpPerLevelEntry(
                (uint)row[0],
                (uint)row[1],
                (uint)row[2],
                (uint)row[3],
                (uint)row[4],
                (uint)row[5]
            ));
        return list;
    }
}
