<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NexusUnleashed.Network\NexusUnleashed.Network.csproj" />
    <ProjectReference Include="..\NexusUnleashed.GameData\NexusUnleashed.GameData.csproj" />
    <ProjectReference Include="..\NexusUnleashed.Sts\NexusUnleashed.Sts.csproj" />
  </ItemGroup>
</Project>
